### ISSUE TITLE
Incorrect mode (SGID bit set) for directories created via overlay.d in fedora-coreos-config

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-tracker#1003] opened 2021-10-22 10:36 UTC
**Describe the bug**

Directories created via `overlay.d` in fedora-coreos-config are created with the SGID bit set:

```
$ sudo find /usr /etc -type f,d -perm /2000
/usr/bin/write
/usr/lib/coreos
/usr/lib/dracut/modules.d/10coreos-sysctl
/usr/lib/dracut/modules.d/25coreos-azure-udev
/usr/lib/dracut/modules.d/35coreos-ignition
/usr/lib/dracut/modules.d/35coreos-live
/usr/lib/dracut/modules.d/35coreos-multipath
/usr/lib/dracut/modules.d/35coreos-network
/usr/lib/dracut/modules.d/40ignition-conf
/usr/lib/dracut/modules.d/40ignition-ostree
/usr/lib/dracut/modules.d/50coreos-kernel
/usr/lib/dracut/modules.d/50ignition-conf-fcos
/usr/lib/dracut/modules.d/60coreos-agetty-workaround
/usr/lib/dracut/modules.d/99emergency-timeout
/usr/lib/dracut/modules.d/99journal-conf
/usr/lib/systemd/journald.conf.d
/usr/lib/systemd/system/emergency.service.d
/usr/lib/systemd/system/kdump.service.d
/usr/lib/systemd/system/multipathd.socket.d
/usr/lib/systemd/system/rescue.service.d
/usr/lib/systemd/system/systemd-firstboot.service.d
/usr/libexec/openssh/ssh-keysign
/usr/libexec/utempter/utempter
/usr/share/licenses/fedora-coreos-config
```

To check for both SUID & SGID:

```
$ sudo find /usr /etc -type f,d -perm /6000
...
```

Some files/directory listed here are valid usage of the SGID bit. We should make a test with an allowlist for both SUID & SGID.

**Reproduction steps**

N/A

**Expected behavior**

No SGID bit set on directories.

**Actual behavior**

SGID bit set on directories.

**System details**

 - Digital Ocean but likely to apply to all platforms
 - Fedora CoreOS:

```
$ rpm-ostree status
State: idle
AutomaticUpdatesDriver: Zincati
  DriverState: active; periodically polling for updates (last checked Fri 2021-10-22 10:31:52 UTC)
Deployments:
● fedora:fedora/x86_64/coreos/stable
                   Version: 34.20211004.3.1 (2021-10-19T19:21:33Z)
                BaseCommit: a44c3b4d10b94db300d420cba76249b6c6de368fa1f93613796e50d3ee8b3568
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
           LayeredPackages: zsh vim tmux htop tree

  fedora:fedora/x86_64/coreos/stable
                   Version: 34.20210919.3.0 (2021-10-04T17:11:11Z)
                BaseCommit: 6334e11901fba7403600522286d817b520eeb15b66b341b392e0c08ed2576b74
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
           LayeredPackages: zsh vim tmux htop tree
```

**Comment by jlebon** [comment] 2021-11-03 15:15
This is fixed by https://github.com/coreos/coreos-assembler/pull/2537. It doesn't happen in CoreOS CI because the SA has a looser SCC.

**Comment by jlebon** [comment] 2021-11-04 15:55
Confirmed fixed in latest builds with https://github.com/coreos/coreos-assembler/pull/2537.

```
[root@cosa-devsh ~]# find /usr /etc -type f,d -perm /2000
/usr/bin/write
/usr/libexec/openssh/ssh-keysign
/usr/libexec/utempter/utempter
```

**Closed by jlebon** 2021-11-04 15:55 UTC
Labels: kind/bug, jira

**Comment by dustymabe** [comment] 2021-11-11 15:53
The fix for this went into next stream release `35.20211107.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment] 2021-11-11 16:29
The fix for this went into testing stream release `35.20211029.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment] 2021-11-11 16:29
The fix for this went into stable stream release `34.20211031.3.0`.
