### ISSUE TITLE
Error instaling perl - sudo rpm-ostree install perl - fedora-coreos-32

### ISSUE THREAD

**Issue by ricardo-rod** [coreos/fedora-coreos-tracker#595] opened 2020-08-05 19:37 UTC
**Host system details**

Provide the output of `rpm-ostree status`.
sudo rpm-ostree status

State: idle
Deployments:
● ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 32.20200715.3.0 (2020-07-27T11:36:29Z)
                    Commit: a3b08ee51b1d950afd9d0d73f32d5424ad52c7703a6b5830e0dc11c3a682d869
              GPGSignature: Valid signature by 97A1AE57C3A2372CCA3A4ABA6C13026D12C944D0

**Expected vs actual behavior**

```
sudo rpm-ostree install perl

Checking out tree a3b08ee... done
Enabled rpm-md repositories: fedora-cisco-openh264 updates fedora
Updating metadata for 'fedora-cisco-openh264'... done
rpm-md repo 'fedora-cisco-openh264'; generated: 2020-03-17T20:10:45Z
Updating metadata for 'updates'... done
rpm-md repo 'updates'; generated: 2020-08-05T00:56:59Z
Updating metadata for 'fedora'... done
rpm-md repo 'fedora'; generated: 2020-04-22T22:22:36Z
Importing rpm-md... done
⠁  
Forbidden base package replacements:
  libgomp 10.1.1-1.fc32 -> 10.0.1-0.11.fc32 (fedora)
  libstdc++ 10.1.1-1.fc32 -> 10.0.1-0.11.fc32 (fedora)
This likely means that some of your layered packages have requirements on newer or older versions of some base packages. Doing `rpm-ostree cleanup -m` and `rpm-ostree upgrade` first may help. For more details, see: https://github.com/projResolving dependencies... done
error: Some base packages would be replaced

```

Expected:

```
# sudo rpm-ostree install perl
...
Success!
```

**Steps to reproduce it**

$ hostnamectl 
   Static hostname: localhost
         Icon name: computer-vm
           Chassis: vm
        Machine ID: e969a2df676d4aa2b44cff4bd6f656e1
           Boot ID: d80bfc1d2ae74211a75573fec521d10a
    Virtualization: vmware
  Operating System: Fedora CoreOS 32.20200715.3.0
       CPE OS Name: cpe:/o:fedoraproject:fedora:32
            Kernel: Linux 5.7.8-200.fc32.x86_64
      Architecture: x86-64

```
sudo rpm-ostree install perl
sudo rpm-ostree cleanup -m
sudo rpm-ostree upgrade
sudo rpm-ostree install perl
```

**Would you like to work on the issue?**

I can work but i do not know how to fix it, but I can try it.

**Comment by lucab** [comment] 2020-08-06 08:55
Thanks for the report. I've moved this to the Fedora CoreOS tracker, as it is an issue with the packages/repositories there.

This is a duplicate of https://github.com/coreos/fedora-coreos-tracker/issues/400, which is a larger problem between ostree and Fedora repositories.

In general, you shouldn't be installing `perl` or anything else directly on the host system. Instead, please consider bringing whatever Perl application you have on your radar into a container.

**Comment by lucab** [comment] 2020-08-06 11:05
I'm closing this as a duplicate of #400. @ricardo-rod if you are dealing with some third-party Perl application, my suggestion would be reach out on their forum about how to run that from a container.

**Closed by lucab** 2020-08-06 11:05 UTC
