### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#194] opened 2019-05-31 04:39 UTC
In Container Linux we never really got [release notes](https://coreos.com/releases/) right:
- The notes for a release are manually constructed, which can be time-consuming.
- To correctly determine the complete set of changes after a cross-channel promotion, users must understand the CL branching model, which is not obvious or documented (https://github.com/coreos/bugs/issues/2134).
- Release notes are available on a web page, and in a JSON doc which requires custom tooling to read (i.e., is not RSS or Atom).  There's no good way to receive notifications when new release notes are available (except for subscribing to the repo where the release notes are pushed).
- Documentation does not explicitly recommend reading release notes, but a prudent user will do so anyway.
- Release notes are generally considered immutable, and are not changed even if incorrect or incomplete.
- The docs site takes half an hour to build, imposing a 30- to 90-minute delay between release of artifacts and publication of release notes.

We should design the release notes for Fedora CoreOS.

- Should they be automatically generated?  From what inputs?
- Should we provide tools for showing all changes between two versions?
- Should notes be revised if later determined to be incorrect?  (e.g., a fix was ineffective)
- Should notes be revised if a release is later determined to introduce an important bug?
- Where should release notes be published?  Presumably a web page.  RSS/Atom feed?  Mailing list?  Release and/or stream metadata?
- Where should the authoritative copy of release notes be stored, and how should it be propagated to other copies?

**Comment by jlebon** [comment] 2019-06-12 17:07
Just a random note: rpm-ostree has some nice tooling, albeit targeted for the client side, surrounding the question "what changed?".

1. it can download and display security errata for packages and extract CVE information from their synopses
2. `rpm-ostree db diff --changelogs` gives you a full summary of what changed in packages between two versions

Definitely open to rework those to make them more accessible if they'd be useful in whatever workflow we establish.

**Comment by bgilbert** [comment] 2019-06-21 04:57
Discussed at [last week's meeting](https://meetbot.fedoraproject.org/teams/fedora_coreos_meeting/fedora_coreos_meeting.2019-06-12-16.30.html).

FAH release notes consist of an [automated email](https://lists.projectatomic.io/projectatomic-archives/atomic-devel/2019-June/msg00000.html) and a [followup](https://lists.projectatomic.io/projectatomic-archives/atomic-devel/2019-June/msg00002.html).  The latter can have [handwritten content](https://lists.fedoraproject.org/archives/list/rel-eng@lists.fedoraproject.org/message/5WBUM4XTZA7FZQZ3SVDH5GMWRH6472H2/).  These messages are sent only for stable releases, and aren't archived anywhere other than the mailing lists.

Our release notes could have several sections:
- A manually-curated set of important information: major changes, notable security or bug fixes
- Perhaps a list of package versions for important packages, as CL does
- Automatically generated list of CVEs
- Something like `rpm-ostree db diff --changelogs`, which lists the relevant parts of package changelogs.  We could filter the package set, or float important packages to the top.  For new upstream releases of relevant packages, we could automatically link to the upstream release notes.

We should have a permalink for each set of release notes.  We might want to use several publication methods, as different users may have different preferences: mailing list, RSS, Twitter, etc.

**Comment by dhawal55** [comment] 2020-03-31 13:32
Any update on this? What are the plan for release notes? Can we at least start with something simple and build upon it?

**Comment by jlebon** [comment] 2020-03-31 15:09
Re. authoritative source, one simple idea to get started is just a `release.md` in https://github.com/coreos/fedora-coreos-config production branches. I.e. this naturally ties the release notes to the content promotion process and we can have it be generated at that time, and reviewed, and merged atomically with the content, etc... (Guess it could be as the commit message too, though GitHub doesn't make reviewing commit messages easy, and it's less flexible in case we want to fix up a typo or something).

**Comment by jlebon** [comment] 2020-03-31 15:11
> Where should release notes be published? Presumably a web page.

Not sure if we want to maintain a separate site from https://getfedora.org/en/coreos, so my vote is to keep it there. This argues for putting it in the stream metadata of course, but we're not necessarily tied to that either and could have the notes fetched from somewhere else.

**Comment by mariusgrigoriu** [comment] 2020-05-05 18:04
Until we figure out how changelogs are published, what is the recommended way to get a sense of what's new with any given release prior to taking an update?

**Comment by jlebon** [comment] 2020-05-06 15:51
> Until we figure out how changelogs are published, what is the recommended way to get a sense of what's new with any given release prior to taking an update?

@zonggen is working on a redesign of the download page that will show the package list and package diff at least until we enhance it with nicer release notes.

For now, you can do something like:

```
# ostree pull fedora:fedora/x86_64/coreos/stable
# rpm-ostree db diff fedora:fedora/x86_64/coreos/stable --changelogs
```

**Comment by fifofonix** [comment] 2020-05-29 00:13
The newly re-worked release pages with the summaries of changed packages are a definite plus but I think the 'next' stream should be calling out the docker version change to 19.03.8 from 18.09.8 as a top-level change right now.  Just like there are call outs for versions of ignition/podman etc.

I'm not sure how this all comes together but I did do an `rpm-ostree db list` on next and grepped for docker to no avail to confirm why the docker change isn't even actually listed in the full listing.  I guess it is layered into the build in a way that I'm not appreciating?  Perhaps these additional pieces need to be scanned somehow for versions when building auto release highlight pages to give them visibility.

**Comment by bgilbert** [comment] 2020-05-29 00:45
@fifofonix The package you're looking for is `moby-engine`.

**Comment by fifofonix** [comment] 2020-05-29 01:14
Got it.  And yes of course that is in the full list of packages.  But I still think it deserves a more obvious call out.

**Comment by dustymabe** [comment] 2020-05-29 04:05
@zonggen - can we add `moby-engine` to the short list of packages that get highlighted for each release of FCOS on the [release notes page](https://getfedora.org/en/coreos?stream=stable)?

**Comment by zonggen** [comment] 2020-05-29 13:47
@dustymabe Sure. For reference, we have a list of important packages to show in the release browser and the download page:
 - https://github.com/coreos/fedora-coreos-browser/blob/master/index.html#L194
 - https://pagure.io/fedora-web/websites/blob/master/f/sites/static/js/coreos-release-notes.js#_21

Filed https://pagure.io/fedora-web/websites/pull-request/118

**Comment by dustymabe** [comment] 2020-06-24 19:10
We discussed this in the [meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/LR55AGRUQFNXH4V3BZCTGALQTSEAC2ZC/).

In general I think we agreed that we could use a file (probably yaml) in the tip of each production stream (`stable`, `testing`, `next`) to collect release note information about each release in that stream. How we plumb that through to get to the release notes on the website is still up for discussion.

Another idea was that we come up with a way to add release notes as we merge in PRs. So something like a `release-notes.d/` directory in the `testing-devel` branch where each new PR could add content there (unique file names avoid merge conflicts) and then it gets collated together when we do a release.

**Comment by zonggen** [comment] 2020-07-13 21:16
Does the following design sound feasible:
 - Include a changelog.yml file inside each of the build directory (or changelog.d/ that contains the yaml files)
 - merge the yaml files from last release build upto the next release builds into a single release changelog file, and also de-dup the changelog
 - release page use the final changelog yaml file to display desired information

Though this sounds like a naive solution..

**Comment by dustymabe** [comment] 2020-07-20 15:14
> Does the following design sound feasible:
> 
>* Include a changelog.yml file inside each of the build directory (or changelog.d/ that contains the yaml files)

What do you mean by "build directory" here? Are you referring to having a file or directory in each branch of the fcos configs repo?

>
>* merge the yaml files from last release build upto the next release builds into a single release changelog file, and also de-dup the changelog

Yep. I'm thinking that when we take the contents from the `/.d` directory on the `testing-devel` stream and merge it together and put it under a `nextrelease` entry in the yaml.

Once we do the release we update the entry in the yaml to be the version number from the build we just put out. 

Example toplevel yaml:

```
releases:
  - nextrelease:
    - removed package xyz
        - This package was causing problems. Workaround by foo foo foo.
    - added package abc
    - fixed [bug3](https://example.com/bug3)
  - 32.20200629.3.0:
    - removed package xyz
    - added package abc
    - fixed [bug4](https://example.com/bug3)
```

`nextrelease` would then get replaced when we put out the release. There are a lot of mechanics here and a lot of ways to do this. I think the important part is that we get something in place and then start ot iterate on it. 

>
>* release page use the final changelog yaml file to display desired information

👍

Another thing to think about is the format of the yaml file. Would we accept markdown and then try to render it as html?

**Comment by zonggen** [comment] 2020-07-20 15:57
> What do you mean by "build directory" here? Are you referring to having a file or directory in each branch of the fcos configs repo?
Yes, I was thinking about adding `/.d` or a `.yaml` in each branch of fcos config repo.

>  the important part is that we get something in place and then start ot iterate on it.
:+1: I will start experimenting from the basic approach and see how it looks.

> Would we accept markdown and then try to render it as html?
Parsing markdown into html and inject into Vue.js code is feasible however may require additional dependencies, but I do think markdown is much more readable so will experiment with the dependencies. Yaml and json parser is built into javascript so reading them should be straightforward.

**Comment by zonggen** [comment] 2020-08-05 21:34
Further discussion with @dustymabe leads to the following design. 

The reason for separating out the release notes creation from FCOS pipeline is that when we want to make adjustment to the old release notes we've already published, we can manually update the `release-notes.yaml` entry for that release and update the website, independent of release cycles.

### Developement situation:
1. Developer A opens PR to testing-devel repo to fedora-coreos-config repo
    - adds release note to release-notes.d/fixed-ignition-bug.yaml
        - fixed bug [77](https://link/to/bug/77) in ignition all nodes now use DHCP
    - PR gets merged
2. Developer B opens PR to testing-devel repo to fedora-coreos-config repo
    - adds release note to release-notes.d/fixed-afterburn-bug.yaml
        - fixed bug 87[https://link/to/bug/87] in afterburn all nodes now use ecdsa SSH keys
    - PR gets merged
3. We want to do a `testing` release
    - merge `testing-devel` into `testing`
    - run a build through the build pipeline
        - this is the step where we learn what the version number is (i.e. 32.20200629.3.0)
    - we do some final checks (mostly just little inspections)
    - then we run the release pipeline
        - replicates to aws regions
        - copies ostree content to prod repo
    - then we run fedora-coreos-stream-generator
        - metadata processing
    - copy metadata to S3
        - Update server (cincinatti) picks up new metadata from s3, serves updates 
        - Website picks up new metadata from s3, serves updates

_Note_: In the case of overgrowing `release-notes.yaml`, do `mv releasenotes.yaml 2020-releasenotes.yaml` annually (or periodically)

### Proposal:

Have a tool that runs independently of the pipeline like `bump-lockfile` and `sync-stream-metadata` jenkins jobs. This tool will trigger based on a new release of FCOS or can be triggered manually. The responsibility of this tool includes:


#### Git repository manipulation
- look at the `release-notes.yaml` file for the related branch (i.e. `testing`)
    - if an entry for that release exists, it does nothing to the git repo
    - if an entry for that release does not exist
        - create a new entry in `release-notes.yaml` for that release version
            - merge the `release-notes.d/*` files into `release-notes.yaml`
            - delete `release-notes.d/*` files from that branch
            - delete corresponding `release-notes.d/*` files from `testing-devel` branch

#### Intermediate processing to get into ideal form for website code consumption
- process `release-notes.yaml` (maybe convert to JSON or other formats)

#### Upload to place where website can consume
- merge the `release-notes.d/*` files in the related branch (i.e. `testing`) into the `release-notes.yaml` file and conditionally create a new entry for that release:
```
    releases:
      - 32.20200629.3.0:
        - inline: |
            - fixed bug [77](https://link/to/bug/77) in ignition all nodes now use DHCP
            - fixed bug [87](https://link/to/bug/87) in afterburn all nodes now use ecdsa SSH keys
      - 32.20200619.3.0:
        - DISCLAIMER: There was a serious flaw affecting this release that causes AWS nodes to reboot after 4 hours of uptime.
        - old release note 1
        - old release note 2
  ```
- upload to s3
- push commit to testing-devel branch to delete existing `release-notes.d/*` files
- `release-notes.yaml` picked up by FCOS release-notes.js for rendering

**Comment by zonggen** [comment] 2020-08-07 19:59
- [x] Create a `release-notes.d` directory that stores the pre-mature release note yaml snippets (https://github.com/coreos/fedora-coreos-config/pull/550)
 - [x] Create a `release-note-generator` script that merges the pre-mature yaml snippets and writes to the `next-release` field of `release-notes.yaml` (https://github.com/coreos/fedora-coreos-releng-automation/pull/119)
 - [ ] Enable `release-note-generator` script to replace the `next-release` key with the corresponding build id
 - [ ] Add a separate job in `fedora-coreos-pipeline` that automates release note generation and cleanup step for yaml snippets as well as the step to push to S3 bucket
 - [ ] Pick up `release-note.yaml` from Fedora CoreOS website and nicely render the release notes

**Comment by egeturgay** [comment] 2021-03-19 12:30
It would be great if the team consider some improvements on the release notes, particularly on the CVEs. Visibility in CVEs allow us to choose to upgrade or hold on to a specific release. It's an important set of information for various compliance requirements.
We currently workaround it by running the below and looking up CVE severity manually on the web.
`ostree pull fedora:fedora/x86_64/coreos/stable && rpm-ostree db diff fedora:fedora/x86_64/coreos/stable --changelogs | grep -A 1 -B 3 CVE`

**Comment by bgilbert** [comment] 2021-03-23 00:16
> Visibility in CVEs allow us to choose to upgrade or hold on to a specific release. It's an important set of information for various compliance requirements.

@egeturgay Could you expand on that a bit?  Any CVEs that apply to a new release are likely to apply to previous releases as well, so when would CVE metadata cause you not to upgrade?

**Comment by egeturgay** [comment] 2021-03-23 10:33
@bgilbert we wouldn't upgrade to a newer release if the CVEs are attributed with a low score (low, moderate etc) and if they don't affect the services we run (e.g. cups, samba), we may choose to not upgrade until we come across a high risk fix. 
We replace the instances with the new releases based on these after testing them rather than using the in-place auto update to ensure we don't experience  any regressions.

Sometimes regressions can be side effects of a newer version of the OS components, for example the recent systemd version upgrade broke fluentd systemd integration which stopped all logging. 

We may choose to upgrade our test systems for a longer period to ensure we don't experience such issues if the CVEs are low enough and reduce the number of re-deployments across our stacks.

**Comment by travier** [comment] 2021-03-24 16:08
For the CVE case more specifically, support may come with https://github.com/coreos/rpm-ostree/issues/1696

**Comment by jlebon** [comment] 2021-03-24 18:05
Re. CVEs, there's a draft PR in https://github.com/coreos/rpm-ostree/pull/2695 which will make this much easier for whatever release notes tooling to query.

**Comment by travier** [comment] 2021-12-13 10:45
In order to make progress on this issue, I'm proposing that we solve a smaller subset of it: linking solved issues from the tracker to releases on the [release page](https://getfedora.org/coreos?stream=stable).

To give an idea about how this would look like for the last couple of releases, you can look at: https://travier.github.io/fedora-coreos-tracker/.

The general idea would be to create three JSON files in this repo, one for each stream, and list the issues referenced for each releases:

```
$ cat testing.json
{
  {
    release: "XXXX.Y.Z",
    issues:
    [
      "X", <-- issue numbers only or title + issue number
      "Y",
      "Z",
    ]
  },
  ...
}
```

The release page could then lazily load those JSON documents and display the issue numbers and titles, fetched from GitHub, or directly included in the JSON files. Having the full titles directly in the JSON means that we do less network calls on the release page but it makes updating them less easy.

This is partially inspired by https://www.flatcar-linux.org/releases/.

**Comment by travier** [comment] 2021-12-13 11:08
Examples:
- https://github.com/travier/fedora-coreos-tracker/blob/main/docs/stable.json
- https://github.com/travier/fedora-coreos-tracker/blob/main/docs/testing.json
- https://github.com/travier/fedora-coreos-tracker/blob/main/docs/next.json

**Comment by dustymabe** [comment] 2022-01-13 16:30
We discussed this in the [community meeting yesterday](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/Q2JPX6OUK4IN5KSNATMJCWYGOZEGBTFA/).

There was no opposition to the idea considering anything is an improvement over what we currently have. There was some interest in the finer details of how to achieve the goal with the least maintenance burden. @travier can you lead the conversation about those details going forward?

**Comment by travier** [comment] 2022-01-18 17:56
The general idea is to dynamically load the JSON with the list of issues on the release page: https://getfedora.org/en/coreos?stream=stable
The main question is:
- where do we store those JSON files? Storing them in this repo might keep things easier as we can quickly link them into a PR.
- who updates them? I can keep doing it as before or share with @dustymabe as he does the `#label` cleanup for each release.

**Comment by travier** [comment] 2022-06-08 10:43
PRs for this work:

Done:
- https://github.com/coreos/fedora-coreos-streams/pull/477
- https://github.com/coreos/fedora-coreos-streams/pull/507
- https://github.com/coreos/fedora-coreos-pipeline/pull/501

In progress:
- https://pagure.io/fedora-web/websites/pull-request/246
- https://github.com/coreos/fedora-coreos-streams/pull/493

**Comment by dustymabe** [comment] 2022-06-10 13:49
Website PR merged:

![Screenshot 2022-06-10 at 09-48-56 Get Fedora](https://user-images.githubusercontent.com/4530030/173079987-c36b1a6d-4f92-4b24-a3c7-e0e52a1336b1.png)


Nice work @travier @mohelt !

**Comment by travier** [comment] 2022-06-10 14:40
I'm closing this one given that we now have release notes available on the website!

I've created https://github.com/coreos/fedora-coreos-tracker/issues/1227 to track future enhancements.

**Closed** 2022-06-10 14:40 UTC
Labels: jira, kind/design
