### ISSUE TITLE
rawhide: ext.config.misc-ro failing due to NetworkManager starting in the initramfs on qemu

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#766] opened 2021-03-11 22:18 UTC
```
Mar 11 21:59:19 qemu0 kola-runext-misc-ro[1867]: + on_platform qemu
Mar 11 21:59:19 qemu0 kola-runext-misc-ro[1867]: + grep -q ' ignition.platform.id=qemu ' /proc/cmdline
Mar 11 21:59:19 qemu0 kola-runext-misc-ro[1867]: + fatal 'NetworkManager started in initramfs!'
Mar 11 21:59:19 qemu0 kola-runext-misc-ro[1867]: + echo 'NetworkManager started in initramfs!'
Mar 11 21:59:19 qemu0 kola-runext-misc-ro[1867]: NetworkManager started in initramfs!
Mar 11 21:59:19 qemu0 kola-runext-misc-ro[1867]: + exit 1
Mar 11 21:59:19 qemu0 systemd[1]: kola-runext.service: Main process exited, code=exited, status=1/FAILURE
Mar 11 21:59:19 qemu0 systemd[1]: kola-runext.service: Failed with result 'exit-code'.
--- FAIL: ext.config.misc-ro (56.59s)
        harness.go:714: kolet failed: : kolet run-test-unit failed: Error: Unit kola-runext.service exited with code 1
```

Haven't dug into this yet. It might be the journal grepping that needs tweaking.

**Comment by dustymabe** [comment] 2021-04-14 19:59
Ha. Good ol `rawhide` letting us know there was a problem early. I'll close this one out as a duplicate of https://github.com/coreos/fedora-coreos-tracker/issues/782 since there are more details over there.

Thanks `rawhide` we'll pay more attention to you next time 🙂

**Closed by dustymabe** 2021-04-14 19:59 UTC
Labels: kind/bug
