### ISSUE TITLE
Fix k8s containers secret access being blocked by SELinux

### ISSUE THREAD

**Issue by basvdlei** [coreos/fedora-coreos-tracker#1366] opened 2022-12-29 14:13 UTC
### Describe the bug

Secrets and memory backed emptydir volumes, created by a Kubelet running inside a podman system container, can no longer be accessed by pods after an updating to testing 37.20221225.2.1.

Access is blocked by SELinux:

```
Dec 29 10:13:12 worker-01 audit[7127]: AVC avc:  denied  { open } for  pid=7127 comm="kube-state-metr" path="/var/run/secrets/kubernetes.io/serviceaccount/..2022_12_29_10_05_35.1005894857/token" dev="tmpfs" ino=3 scontext=system_u:system_r:container_t:s0:c159,c820 tcontext=system_u:object_r:tmpfs_t:s0 tclass=file permissive=0
Dec 29 10:14:38 worker-01 audit[7603]: AVC avc:  denied  { open } for  pid=7603 comm="kube-state-metr" path="/var/run/secrets/kubernetes.io/serviceaccount/..2022_12_29_10_05_35.1005894857/token" dev="tmpfs" ino=3 scontext=system_u:system_r:container_t:s0:c159,c820 tcontext=system_u:object_r:tmpfs_t:s0 tclass=file permissive=0
Dec 29 10:17:28 worker-01 audit[8328]: AVC avc:  denied  { open } for  pid=8328 comm="kube-state-metr" path="/var/run/secrets/kubernetes.io/serviceaccount/..2022_12_29_10_05_35.1005894857/token" dev="tmpfs" ino=3 scontext=system_u:system_r:container_t:s0:c159,c820 tcontext=system_u:object_r:tmpfs_t:s0 tclass=file permissive=0
```

Downgrading container-selinux to container-selinux 2:2.193.0-1.fc37.noarch with `rpm-ostree override replace` resolves the issue.

### Reproduction steps

1. Run a Kubelet with Podman privileged container and a volumemount: `--volume /var/lib/kubelet:/var/lib/kubelet:rshared,z`
2. Create a secret and a pod:

```
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque
data:
  USER_NAME: YWRtaW4=
  PASSWORD: MWYyZDFlMmU2N2Rm
---
apiVersion: v1
kind: Pod
metadata:
  name: volumetest
  labels:
    pod-type: testing
spec:
  containers:
  - name: test
    image: registry.fedoraproject.org/fedora:37
    command: ['sh', '-c', 'echo "Hello world" && sleep +inf']
    volumeMounts:
    - mountPath: /test-secret
      name: test-secret
    - mountPath: /test-default-emptydir
      name: test-default-emptydir
    - mountPath: /test-memory-emptydir
      name: test-memory-emptydir
  volumes:
  - name: test-default-emptydir
    emptyDir:
  - name: test-memory-emptydir
    emptyDir:
      medium: Memory
      sizeLimit: 64Mi
  - name: test-secret
    secret:
      secretName: test-secret
```

3.  Look at the SELinux labels of the created volumes:
```
ls -lZ /var/lib/kubelet/pods/*/*
```

### Expected behavior

tmpfs volumes to be labeled with `system_u:object_r:container_file_t:s0` and the pod containers are allowed access:

```
kubernetes.io~empty-dir:
total 0
drwxrwxrwx. 2 root root system_u:object_r:container_file_t:s0  6 Dec 29 13:35 test-default-emptydir
drwxrwxrwt. 2 root root system_u:object_r:container_file_t:s0 40 Dec 29 13:35 test-memory-emptydir

kubernetes.io~projected:
total 0
drwxrwxrwt. 3 root root system_u:object_r:container_file_t:s0 140 Dec 29 13:35 kube-api-access-7v7qb

kubernetes.io~secret:
total 0
drwxrwxrwt. 3 root root system_u:object_r:container_file_t:s0 120 Dec 29 13:35 test-secret
```

### Actual behavior

The volumes backed by a tmpfs filesystem are labeled with `system_u:object_r:container_file_t:s0` and pod container access is denied.

```
kubernetes.io~empty-dir:
total 0
drwxrwxrwx. 2 root root system_u:object_r:container_file_t:s0  6 Dec 29 13:23 test-default-emptydir
drwxrwxrwt. 2 root root system_u:object_r:tmpfs_t:s0          40 Dec 29 13:23 test-memory-emptydir

kubernetes.io~projected:
total 0
drwxrwxrwt. 3 root root system_u:object_r:tmpfs_t:s0 140 Dec 29 13:23 kube-api-access-7lmxp

kubernetes.io~secret:
total 0
drwxrwxrwt. 3 root root system_u:object_r:tmpfs_t:s0 120 Dec 29 13:23 test-secret
```

### System details

- QEMU
- Fedora CoreOS 37.20221225.2.1 (Testing)

### Additional information

I've not tested this, but this issue should affect [Poseidon Typhoon Kubernetes](https://typhoon.psdn.io/fedora-coreos/aws/) on Fedora CoreOS as well, as we are using the same method to run a kubelet with podman: https://github.com/poseidon/typhoon/blob/main/azure/fedora-coreos/kubernetes/workers/butane/worker.yaml#L53

**Comment by dustymabe** [comment] 2022-12-29 23:19
Thanks for the report and for running the `testing` stream. We'll try to figure out the root cause and probably do a revert to the older version in `testing` early next week.

**Comment by dustymabe** [comment] 2023-01-03 04:13
Here are the package pins for this:

- https://github.com/coreos/fedora-coreos-config/pull/2142
- https://github.com/coreos/fedora-coreos-config/pull/2144
- https://github.com/coreos/fedora-coreos-config/pull/2145

**Comment by dustymabe** [comment] 2023-01-04 20:23
The fix for this went into `next` stream release `37.20221225.1.2`. Please try out the new release and report issues.

**Comment by dustymabe** [comment] 2023-01-04 20:23
The fix for this went into `testing` stream release `37.20221225.2.2`. Please try out the new release and report issues.

**Comment by dustymabe** [comment] 2023-01-04 20:28
This issue never affected our `stable` stream.

Even though no current production streams are affected because we are pinned on an older `container-selinux` version I will leave this issue open as the root cause is still outstanding and we need to work with upstream to find a fix.

**Comment by basvdlei** [comment] 2023-01-05 11:35
Thanks! I just spun up a lab cluster with 37.20221225.2.2 and it looks good. Will do some more checks and fix our canary nodes again by rolling out this release.

I've not spent much time looking at the root cause, but I guess https://github.com/containers/container-selinux/pull/196 might be related. For what we do, the expectation is that 'stuff' created in a volume with `:z` is always accessible by other containers.

**Comment by dustymabe** [comment] 2023-01-05 14:44
The commit related to https://github.com/containers/container-selinux/pull/196 is https://github.com/containers/container-selinux/commit/9852880cea1824fa96fcc788f61a97a8234881e7 which is supposedly in [v2.193.0](https://github.com/containers/container-selinux/releases/tag/v2.193.0) so I doubt that's the fix since `container-selinux-2.193.0-1.fc37` is the version we pinned to get back to the good behavior.

**Comment by dustymabe** [comment] 2023-01-05 14:47
@basvdlei - any chance you could come up with a reproducer for this that doesn't involve kubernetes? I'd like to add a test to our CI so that when this does get fixed we won't regress on it, but I'd prefer to not have to have that test run kubernetes if possible (a bit more heavyweight).

**Comment by basvdlei** [comment] 2023-01-05 17:07
@dustymabe Good point.

I believe the issue can reproduced with the following podman commands:

```
# Create a shared volume and mount a tmpfs filesystem inside of it
sudo mkdir /var/lib/testvolume
sudo /usr/bin/podman run --rm --privileged \
  --volume "/var/lib/testvolume:/test:rshared,z" \
  registry.fedoraproject.org/fedora-minimal:37 \
    /bin/sh -c 'mkdir /test/tmpfsmnt && mount -t tmpfs -o size=1436061696 tmpfs /test/tmpfsmnt && echo foo > /test/tmpfsmnt/bar'
```

```
# Try to read from the tmpfs inside the volume with another container
# (this example is a rootless podman container):
podman run \
  --volume "/var/lib/testvolume:/test" \
  registry.fedoraproject.org/fedora-minimal:37 \
    /bin/cat /test/tmpfsmnt/foo
```

Outputs `bar` but results in a `Permission denied` on 37.20221225.2.1.

For Kubernetes it would be a containerd container that will try to read. I did try to reproduce it with ctr commands, but that seems to lack the option to set selinux labels from the cli (or I'm missing it).

**Comment by rhatdan** [comment] 2023-01-05 17:23
This looks like an issue with Kubernetes creating a file to be used inside of a container without the correct label.

path="/var/run/secrets/kubernetes.io/serviceaccount/..2022_12_29_10_05_35.1005894857/token"

Kurnetes when it creates this file it should have the correct label on it.

Is this system using CRI-O or containerd?

**Comment by basvdlei** [comment] 2023-01-05 17:58
@rhatdan the cluster is using containerd. 

But the Kubelet runs inside of a Podman container, just like the Typhoon Kubernetes does on Fedora CoreOS: https://github.com/poseidon/typhoon/blob/main/azure/fedora-coreos/kubernetes/workers/butane/worker.yaml#L37

I've not seen the Kubelet/Kubernetes relabel these files, so we've relied on the shared `container_file_t:s0` until now. But if that's an option that would be great.

But with container-selinux 2:2.195.1-1.fc37.noarch, there is a slight change in behavior in how the tmpfs mounts are labeled when done from inside this podman container. In the smaller reproduction I gave above, using only podman, I'm unable to access the files inside the tmpdir from another podman container, even though the volume is shared `:z`.

**Comment by rhatdan** [comment] 2023-01-05 18:35
Well the run secret is not labeled container_file_t:s0 it is labeled tmpfs_t:s0 which is the wrong label.

You can downgrade the container-selinux if you want to prove me wrong, but I would be very surprised.
This should never be allowed.

**Comment by basvdlei** [comment] 2023-01-05 18:59
Oh sorry, if this was not clear. Downgrading container-selinux from 2:2.195.1-1.fc37.noarch to 2:2.193.0-1.fc37.noarch solves this issue.

I agree that the Kubernetes stuff makes this confusing, but that's the practical use case where this issue popped up.

[This example above]( https://github.com/coreos/fedora-coreos-tracker/issues/1366#issuecomment-1372489061) is using _only_ podman and highlights the issue:

- Create container with a `:rshared,z` volume
- Inside that container mount a tmpfs filesystem in that volume
- Try to access the tmpfs filesystem from another (podman) container using the volume

With container-selinux 2:2.193.0-1.fc37.noarch installed the tmpfs (and it's contents) will be labeled with `container_file_t:s0`. But if upgraded to 2:2.195.1-1.fc37.noarch the contents will be labeled with `tmpfs_t:s0` from the tmpfs mountpoint.

**Comment by rhatdan** [comment] 2023-01-05 19:11
If the label is changing that seems like a kernel issue.  No reason that container-selinux would be changing the label.

If you are mounting a container with a tmpfs within a privileged container that is a tmpf, then I would need to know the label of the process in side of the container, most likely spc_t:s0, then it could be a transition rule, but I am not sure.  With the older container-selinux what label do you see the tmpfs being?

I guess if you can give me a simple repeater.

**Comment by basvdlei** [comment] 2023-01-05 19:43
Yes, the process inside the container is labeled: `system_u:system_r:spc_t:s0`.

With the older (2.193.0-1) the tmpfs is labeled: `unconfined_u:object_r:container_file_t:s0`

Attached 2 logs of the reproduction with the 2 different container-selinux packages: 
[container-selinux-2.193.0-1.txt](https://github.com/coreos/fedora-coreos-tracker/files/10355226/container-selinux-2.193.0-1.txt)
[container-selinux-2.195.1-1.txt](https://github.com/coreos/fedora-coreos-tracker/files/10355225/container-selinux-2.195.1-1.txt)

**Closed** 2023-01-09 15:06 UTC
Labels: kind/bug, status/pending-testing-release, status/pending-next-release

**Comment by dustymabe** [comment] 2023-01-10 17:09
The fix for this went into `next` stream release `37.20230107.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment] 2023-01-10 17:09
The fix for this went into `testing` stream release `37.20230107.2.0`. Please try out the new release and report issues.

**Comment by basvdlei** [comment] 2023-01-11 09:24
Just spun up a cluster without issues on `37.20230107.2.0`. Thanks!

**Comment by dustymabe** [comment] 2023-01-25 15:05
The fix for this went into `stable` stream release `37.20230110.3.1`.
