### ISSUE TITLE
Track which fix/commit is included in official releases?

### ISSUE THREAD

**Issue by remoe** [coreos/fedora-coreos-tracker#505] opened 2020-05-28 16:56 UTC
How one can track which fix/commits are included in official releases: https://getfedora.org/en/coreos/download?tab=cloud_launchable&stream=stable
?

It's interesting to know if a fix (which for example 3 month old) is in one of the current official releases.

**Comment by dustymabe** [comment] 2020-05-29 05:02
It depends. If an issue is reported against our tracker i've been trying to make sure they get updated to note which releases the fix was applied in. For example: https://github.com/coreos/fedora-coreos-tracker/issues/479#issuecomment-628813523

If the issue is in any of the hundreds of upstream projects that make up Fedora CoreOS you'll need to look more at version numbers of components to compare what's in FCOS to what upstream release the issue was fixed in. Luckily we have the rich version information for each package in FCOS. See our [release notes page](https://getfedora.org/en/coreos?stream=stable) which will eventually have more information than just package sets.

**Comment by remoe** [comment] 2020-05-29 06:52
Ok, thanks, I found this https://github.com/coreos/ignition/pull/934 as a sample. I haven't found a reference. Or its not clear what's in the current release about this https://github.com/coreos/fedora-coreos-tracker/issues/368. For example what is the "correct" way to set the SELinux flags in Ignition in current release.

**Comment by lucab** [comment] 2020-05-29 07:53
@remoe as per Ignition release notes, that patch was merged in [https://github.com/coreos/ignition/releases/tag/v2.2.0](https://github.com/coreos/ignition/releases/tag/v2.2.0).

**Comment by dustymabe** [comment] 2020-05-29 16:01
Hi @remoe. Regarding #368 the current answer is still https://github.com/coreos/fedora-coreos-tracker/issues/368#issuecomment-581626419 - we're working to improve the state of things here, but we're working through other backlog items first.

**Comment by dustymabe** [comment] 2020-05-29 16:01
I'm going to close this since it was a question and at least some of an answer was given in https://github.com/coreos/fedora-coreos-tracker/issues/505#issuecomment-635760643

**Closed by dustymabe** 2020-05-29 16:01 UTC
