### ISSUE TITLE
kola: s390x: ext.config.extensions.package failing in %prein for unbound-anchor

### ISSUE THREAD

**Issue by LakshmiRavichandran1** [coreos/fedora-coreos-tracker#1265] opened 2022-07-27 15:57 UTC
**Describe the bug**
ext.config.extensions.package test seems to fail often on s390x with `error: Running %prein for unbound-anchor: bwrap(/bin/sh): Child process killed by signal 6; run `journalctl -t 'rpm-ostree(unbound-anchor.prein)'` for more information`

```
15:26:43  Jul 27 13:26:31 qemu0 kola-runext-package[2046]: Importing packages...done
15:26:43  Jul 27 13:26:40 qemu0 kola-runext-package[2046]: Checking out packages...done
15:26:43  Jul 27 13:26:42 qemu0 kola-runext-package[2046]: Running pre scripts...done
15:26:43  Jul 27 13:26:42 qemu0 kola-runext-package[2046]: error: Running %prein for unbound-anchor: bwrap(/bin/sh): Child process killed by signal 6; run `journalctl -t 'rpm-ostree(unbound-anchor.prein)'` for more information
15:26:43  Jul 27 13:26:42 qemu0 systemd[1]: kola-runext.service: Main process exited, code=exited, status=1/FAILURE
15:26:43  Jul 27 13:26:42 qemu0 systemd[1]: kola-runext.service: Failed with result 'exit-code'.
15:26:46  --- FAIL: ext.config.extensions.package (127.00s)
15:26:46          cluster.go:162: Error: Unit kola-runext.service exited with code 1
15:26:46          cluster.go:162: 2022-07-27T13:26:42Z cli: Unit kola-runext.service exited with code 1
15:26:46          harness.go:973: kolet failed: : kolet run-test-unit failed: Process exited with status 1
15:27:01  --- PASS: ext.config.root-reprovision.raid1 (237.20s)
15:27:11  --- PASS: ext.config.ignition.kargs (54.57s)
```

this is a time log of the failures encountered and the respective streams

560 2022-07-27 rawhide [37.20220727.91.0](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/build-arch/560/)
506 2022-07-20 testing-devel  [36.20220720.20.0](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/build-arch/506/)
551 2022-07-26 next [36.20220723.1.2](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/build-arch/551/)
327 2022-07-18 bumplockfile  [36.20220718.dev.0](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/bump-lockfile/327/)

**Reproduction steps**
1. run the kola tests for s390x

**Expected behavior**
the test should pass

**System details**
 - different fcos versions on s390x arch

**Additional information**
Add any other information about the problem here.
interestingly, the issue had occured on x86 branch a few months ago in 35.20220324.20.2, but we no longer have logs for that build and there was no explicit fix at that time.

**Comment by LakshmiRavichandran1** [comment] 2022-07-27 16:00
@lucab do you have any hint or a closer look on the failures from the view of updates and remoting team?
from the slack discussion with Dusty, may be some issue with `rpm-ostree`

**Comment by dustymabe** [comment] 2022-07-27 18:56
The `%pre` scriptlet for `unbound-anchor` looks like this:

```
%pre anchor
getent group unbound >/dev/null || groupadd -r unbound
getent passwd unbound >/dev/null || \
useradd -r -g unbound -d %{_sysconfdir}/unbound -s /sbin/nologin \
-c "Unbound DNS resolver" unbound
```

- [source](https://src.fedoraproject.org/rpms/unbound/blob/a53f6dc92e2b7108ef76d48367889f37cd263f6d/f/unbound.spec#_339)

**Comment by dustymabe** [comment] 2022-07-27 18:59
The `journal.txt` from [37.20220727.91.0](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/build-arch/560/) shows:

```
Jul 27 13:26:41.964806 rpm-ostree(unbound-anchor.prein)[2148]: groupadd: /etc/group.4: lock file already used                         
Jul 27 13:26:41.969432 rpm-ostree(unbound-anchor.prein)[2148]: groupadd: cannot lock /etc/group; try again later.                     
Jul 27 13:26:42.066145 rpm-ostree(unbound-anchor.prein)[2152]: useradd: group 'unbound' does not exist
```

Could this possibly be another symptom of the root cause of https://github.com/coreos/fedora-coreos-tracker/issues/1250 ?

cc @lucab

**Comment by lucab** [comment] 2022-07-28 07:11
I think so.

**Comment by lucab** [comment] 2022-08-02 12:49
Closing as a duplicate of https://github.com/coreos/fedora-coreos-tracker/issues/1250

**Closed by lucab** 2022-08-02 12:49 UTC
Labels: kind/bug
