### ISSUE TITLE
Safari web browser replaces query parameter arch=aarch64 with arch=x86_64 for https://getfedora.org/en/coreos/download

### ISSUE THREAD

**Issue by eriksjolund** [coreos/fedora-coreos-tracker#1351] opened 2022-11-24 14:53 UTC
### Describe the bug

Query string for https://getfedora.org/en/coreos/download does not work with Safari (macBook Pro M1). The query parameter _arch=aarch64_ is ignored and automatically changed to _arch=x86_64_.

### Reproduction steps

1. Click the link
https://getfedora.org/en/coreos/download?tab=cloud_launchable&stream=stable&arch=aarch64
with the web browser __Safari Version 16.1 (17614.2.9.1.13, 17614)__
on a  _MacBook Pro (13-inch, M1, 2020)_ with __macOS Monterey 12.6.1__

### Expected behavior

A web page is loaded. The web page contains the text:
_Architecture: aarch64_

The URL bar shows:
_https://getfedora.org/en/coreos/download?tab=cloud_launchable&stream=stable&arch=aarch64_

### Actual behavior

A web page is loaded. The web page contains the text: 
_Architecture: x86_64_

The URL bar shows:
_https://getfedora.org/en/coreos/download?tab=cloud_launchable&stream=stable&arch=x86_64_

### System details

 Web browser __Safari Version 16.1 (17614.2.9.1.13, 17614)__
on a  _MacBook Pro (13-inch, M1, 2020)_ with __macOS Monterey 12.6.1__

**Comment by dustymabe** [comment] 2023-01-10 21:52
I'm able to reproduce this behavior on Firefox on Linux.

**Comment by typecasto** [comment] 2023-02-09 17:40
Same here using Vivaldi on Arch Linux.

**Comment by dustymabe** [comment] 2023-02-09 20:54
This is no longer a problem in the new website re-design (see https://github.com/coreos/fedora-coreos-tracker/issues/1387).

i.e. https://fedora.gitlab.io/websites-apps/fedora-websites/fedora-websites-3.0/coreos/download/?stream=testing&arch=s390x seems to work.

At this point it's not worth fixing the old code since the new code will be in place soon enough.

**Closed by dustymabe** 2023-02-09 20:54 UTC
Labels: kind/bug, jira

**Comment by tnk4on** [comment] 2023-12-29 13:32
I have recently accessed the site and there is an architectural glitch different from the one presented.

The following steps will reproduce the problem.
1. Access the Fedora CoreOS page (https://fedoraproject.org/coreos/).
2. Select the 'Download' link.
3. Choose 'Show Downloads' under 'Testing.'
4. Select each download link listed under 'Virtualized'(In this step, x86_64 will be displayed).
5. After that, choose the 'aarch64' architecture, then select each download link listed under 'Virtualized.

The resulting link is shown below.
```
x86_64
- Apple Hypervisor --> hyperv.x86_64.vhdx.zip
- Hyper-V --> qemu.x86_64.qcow2.xz
- QEMU --> virtualbox.x86_64.ova
- VirtualBox --> vmware.x86_64.ova

aarch64
- Apple Hypervisor --> hyperv.x86_64.vhdx.zip
- Hyper-V --> qemu.x86_64.qcow2.xz
- QEMU --> virtualbox.x86_64.ova
```

**Comment by tnk4on** [comment] 2023-12-29 13:34
The HTML source for Testing (x86_64 and aarch64).
[html_files.zip](https://github.com/coreos/fedora-coreos-tracker/files/13793872/html_files.zip)
