### ISSUE TITLE
rpm-ostree install fail2ban fails with core dump

### ISSUE THREAD

**Issue by millerthegorilla** [coreos/fedora-coreos-tracker#685] opened 2020-11-30 17:52 UTC
**Describe the bug**
when trying to install fail2ban rpm-ostree crashes with 
I check journalctl -xe as advised and systemd-coredump reports process xxx (rpm-ostree) of user 0 dumped core:
Stack trace of thread 2382:
#0 0x000000000b62b5d30 strchrnul (libc.so.6 + 0x80d30)

**Reproduction steps**
1. sudo rpm-ostree install fail2ban 
2. crash listed following running prescripts - error:  Bus owner changed, aborting.  This likely means the daemon crashed: check logs....
3. journalctl -xe reports coredump as above

**Expected behavior**
expected the package fail2ban to install.   It is included in the Fedora 33 repos as standard.  Perhaps it is not included with rpm-ostree repositories?
**Actual behavior**
A clear and concise description of what actually happened.
crash occurs
**System details**
 - Bare Metal/QEMU/AWS/GCP/etc.   Raspberry Pi 2b
 - Fedora CoreOS version  ostree_version 33.20201124.0     ----  Fedora IOT

**Ignition config**   doh.   no idea
Please attach your FCC or Ignition config used to provision your system. Be sure to sanitize any private data. If not using FCCT to generate your Ignition config, does the Ignition config pass validation using [ignition-validate](https://coreos.github.io/ignition/getting-started/#config-validation)?

**Additional information**
Add any other information about the problem here.

**Comment by jlebon** [comment] 2020-11-30 19:05
Dupe of https://bugzilla.redhat.com/show_bug.cgi?id=1900382. If possible, can you post there with the details requested in https://bugzilla.redhat.com/show_bug.cgi?id=1900382#c3?

**Closed by jlebon** 2020-11-30 19:05 UTC
Labels: kind/bug
