### ISSUE TITLE
where should rpm-ostree project live

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#19] opened 2018-07-27 18:58 UTC
I think this one is up to @cgwalters, but figured I'd start the conversation. Some options include:

- github.com/coreos org
- github.com/ostreedev
- leave it where it is (will want to move it eventually)
- new org?

**Comment by cgwalters** [comment] 2018-07-27 19:02
It also goes right into https://github.com/projectatomic/rpm-ostree/issues/405

**Comment by dustymabe** [comment] 2018-07-27 19:09
> It also goes right into projectatomic/rpm-ostree#405

would a potential rename dictate where we move the project?

**Comment by jlebon** [comment] 2018-07-27 20:37
`coreos/rpm-ostree` sounds cool. Though given that rpm-ostree will still be heavily used in other contexts (e.g. Silverblue and IoT), I think I'm leaning more towards `ostreedev/rpm-ostree`? (We could also make it a new org, though `rpm-ostree/rpm-ostree` will be twice as painful if we ever do rename the project).

**Comment by dustymabe** [comment] 2018-07-27 20:39
> though rpm-ostree/rpm-ostree will be twice as painful if we ever do rename the project).

:rofl:

**Comment by sanjabonic** [comment] 2018-07-28 17:05
I discussed this with Colin face to face as well. It's a good time to revisit the name *now*. Alternatively, live with it and definitely plan *not* to rename from now on, then put it under its own organization. I am strongly against putting it under CoreOS due to the reasons @jlebon mentioned above.

**Comment by cgwalters** [comment] 2018-08-01 16:38
> I think I'm leaning more towards ostreedev/rpm-ostree

Mmmm.  Not unreasonable but undercuts some the rationale behind having it be a separate org in the first place - the idea here is that e.g. Debian or OpenEmbedded or whatever should feel that as ostree upstream we'll make sure to consider their needs too.  Whereas rpm-ostree was intended to be fairly opinionated - e.g. we don't even really try to support non-Fedora-derived content sets today.  Having them in the same org is a little weird from that perspective - but I'm not opposed to it either.

How about `coreos/coreos-img`?

**Comment by dustymabe** [comment] 2018-08-01 18:00
> Mmmm. Not unreasonable but undercuts some the rationale behind having it be a separate org in the first place - the idea here is that e.g. Debian or OpenEmbedded or whatever should feel that as ostree upstream we'll make sure to consider their needs too. Whereas rpm-ostree was intended to be fairly opinionated - e.g. we don't even really try to support non-Fedora-derived content sets today. Having them in the same org is a little weird from that perspective - but I'm not opposed to it either.

I think it would only be unreasonable to have it in `ostreedev` if we would **not** accept something like `deb-ostree`(with all of the same customizations for debian) into ostreedev as well. 

 
> How about coreos/coreos-img?

I'd really like to no have the "coreos" word propagate into an infinite number of places like the atomic word did. I still don't see any good reason to rename `rpm-ostree` to something else. It's explicit and makes sense. Either way we should probably not have the re-naming discussion here and should probably keep that in https://github.com/projectatomic/rpm-ostree/issues/405 right?

**Comment by cgwalters** [comment] 2018-08-29 12:43
> I am strongly against putting it under CoreOS due to the reasons @jlebon mentioned above.

To me, the organization denotes *focus* but doesn't imply exclusivity.  If rpm-ostree were part of the coreos/ org, it doesn't mean it can't be used by Fedora IoT or whatever.

**Comment by dustymabe** [comment] 2018-08-29 12:48
Honestly wherever we put it will probably be fine, but I do just want to make one point:

> To me, the organization denotes focus 

This may be a good enough reason for another project to make an *uninformed* decision to not use it. This might be a bad analogy, but if GNOME were under the Fedora organization on GitHub would it be as successful as it is today?

**Comment by cgwalters** [comment] 2018-09-04 17:53
> This might be a bad analogy,

Not sure it's bad, but I am not sure it's useful :smile:  - the ways in which these things are different IMO rather outweigh any similarities.

> Either way we should probably not have the re-naming discussion here

Everything that in issue so far pre-dated the merger.  But I don't have a strong opinion on where the discussion lives, I added a new comment there.

**Comment by dustymabe** [comment] 2018-10-27 14:11
Moving this conversation along. Is it accurate to say these are the two frontrunners?

- github.com/coreos org
- github.com/ostreedev

Maybe we have colin and jonathan (the two main contributors to rpm-ostree) to decide since they have the most invested in the project. Alternatively, if colin and jonathan want other input we can vote in the ticket.

Are there other options, other than the above two that are in the running?

**Comment by jlebon** [comment] 2018-11-28 21:12
Added some thoughts there: https://github.com/projectatomic/rpm-ostree/issues/405#issuecomment-442606179.

> Are there other options, other than the above two that are in the running?

If we definitely decide not to rename, then github.com/rpm-ostree/rpm-ostree ?

**Comment by dustymabe** [comment] 2018-11-28 21:31
so options are:

-   github.com/coreos org
-   github.com/ostreedev org
-   github.com/rpm-ostree org

?? 

Another question.. Does it make a lot of sense to have `ostree` not with `rpm-ostree` ?

**Comment by cgwalters** [comment] 2018-11-28 21:36
There's also https://github.com/rpm-software-management/

**Comment by cgwalters** [comment] 2018-11-28 21:37
> Does it make a lot of sense to have ostree not with rpm-ostree ?

IMO, yes since ostree is used by other projects and I don't want to create the impression that RPM is required by ostree.  I would prefer to keep ostree where it is for now.

**Comment by jlebon** [comment] 2018-11-28 21:41
(Just as a precaution against name squatting, I created https://github.com/rpm-ostree. If we decide to not put it there, I'll delete it.)

**Comment by jlebon** [comment] 2018-11-28 21:50
> There's also https://github.com/rpm-software-management/

Ahh, good one. Of the already existing orgs, that's probably the most appropriate one since being RPM-based is definitely the one property of rpm-ostree that will not change. :) We'll have "rpm" *twice* in the repo URL, so no one can say we're not RPM based! And rpm-ostree also has strong ties to many of the other projects there. My only minor/bikeshed gripe is that it's wordy, but meh.

So now, I'm leaning more towards one of those two:
- github.com/rpm-ostree
- github.com/rpm-software-management

**Comment by dustymabe** [comment] 2018-11-29 14:43
my votes:

- top choice: github.com/ostreedev
- 2nd choice: github.com/rpm-software-management (if they'll have us)

**Comment by LorbusChris** [comment] 2018-12-05 17:41
I like github.com/rpm-software-management/rpm-ostree best

**Comment by LorbusChris** [comment] 2018-12-05 17:42
This encompasses https://github.com/projectatomic/rpm-ostree/issues/405

**Comment by cgwalters** [comment] 2018-12-12 16:36
> github.com/rpm-ostree

A new org just for it?  I dunno, feels like overhead.

> I like github.com/rpm-software-management/rpm-ostree best

I lean towards this, let's ask them.

**Comment by dustymabe** [comment] 2018-12-12 17:34
@jlebon has volunteered to ask the rpm-software-management github org about the move

**Comment by cgwalters** [comment] 2018-12-17 15:03
Although I think we kind of dropped the `github.com/coreos` option without really working through it.  @sanjabonic I am trying to understand https://github.com/coreos/fedora-coreos-tracker/issues/19#issuecomment-408621603 more - it's similar to the Ignition case for example.  I can imagine some IoT use cases (or potentially even Silverblue-style ones) wanting to use Ignition, we wouldn't tell them no right?  (Although it could get weird if e.g. Ignition started learning about desktop-specific things, like how kickstart has a bit of that)

**Comment by jlebon** [comment] 2019-02-19 21:00
Got a response that rpm-software-management would have no problem with rpm-ostree moving there.

> it's similar to the Ignition case for example. I can imagine some IoT use cases (or potentially even Silverblue-style ones) wanting to use Ignition, we wouldn't tell them no right?

Yeah, that's true. Though rpm-ostree is today already pretty focused on supporting both Silverblue and AH/*COS. E.g. there's a lot of UX stuff we've worked on recently that really only benefits the Silverblue use case. That said, at this point, I'd be cool with either `coreos/rpm-ostree` or `rpm-software-management/rpm-ostree`. I completely agree that being under `coreos/` in no way implies we're unfriendly to other use cases. (E.g. etcd was there for a while before finally moving to `etcd-io/`, right?). It's really just a URL string detail in the end. (And much less consequential than the actual project name, discussed in https://github.com/projectatomic/rpm-ostree/issues/405. Though they're of course related).

**Comment by cgwalters** [comment] 2019-02-27 16:15
> Got a response that rpm-software-management would have no problem with rpm-ostree moving there.

OK, let's do that then if there is no one opposed!

**Comment by cgwalters** [comment] 2019-03-15 19:41
I know this is going to suck but I keep having second thoughts on this...the thing is rpm-ostree straddles two entirely different worlds.  On one hand we do want to integrate with the RPM ecosystem - that's not going away.  On the other side...Container Linux IMO is popular because a lot of admins *don't* want to think about packaging.  They like the "image based" background updates - it's a *very* different thing from owning/managing a traditional yum/apt style system.

In the future I'd really like to strengthen rpm-ostree's connection to not-RPM as well - things like [this idea](https://github.com/projectatomic/rpm-ostree/issues/1788).  And here's related food for thought - if there's some software we don't care about shipping in traditional systems, nothing stops us from e.g. building binaries in container images and then converting that to an ostree ref to inject into rpm-ostree.   If we don't care for example about supporting Ignition on traditional RPM based systems we could just build it in a `Dockerfile` or whatever.

That doesn't mean we shouldn't be in the rpm-software-management organization.  But I think it is clear that rpm-ostree isn't just about that.

**Comment by cgwalters** [comment] 2019-09-13 13:45
Since my previous comment, we now support non-RPM content on the compose side, and I do plan to extend that to the client side as noted.  For example, I want to make it easy and convenient to layer a git repository (would work best for noarch content).

Further, one way I often explain the new "CoreOS" is a pairing of (Ignition, ostree) and while I know in FCOS land we have a lot of tension around to what degree we support layered packages etc - I think rpm-ostree would work best in the coreos/ github organization.

I am working on CI related things, specifically integrating with [OpenShift Prow](https://github.com/openshift/release/pull/4979).  I think things will be cleaner if it's in the `coreos/` org.

Any opposition?

**Comment by dustymabe** [comment] 2019-09-13 14:09
> we now support non-RPM content on the compose side

Yeah I just hit this the other day when I was trying to find out where a file came from on the filesystem and no rpm owned it. It would be nice if we have an equivalent to `rpm -qf` inside of `rpm-ostree` that would give us user friendly meaningful infrormation about where the file came from. Maybe I should open an RFE?


> I think things will be cleaner if it's in the coreos/ org.

I still think it would make since to put it in ostreedev, but you have the most say and the greatest context to know where to put it so coreos org sounds good to me.

**Comment by cgwalters** [comment] 2019-09-13 14:11
> Yeah I just hit this the other day when I was trying to find out where a file came from on the filesystem and no rpm owned it. 

Right.  I actually hit this all of the time when I do `podman run -ti somecontainerimage` - I want to know "where did the layered container put its stuff".  I don't even know if there's a convenient CLI way to browse the layers.

I can tell you that having `rpm -qf` do something else will depend on https://github.com/projectatomic/rpm-ostree/pull/1789

**Comment by dustymabe** [comment] 2019-09-13 14:14
> I can tell you that having `rpm -qf` do something else

I'm even looking for a precursor to that next step of *having `rpm -qf` do something else*. If there was the equivalent of an `rpm-ostree -qf` I think that would suffice for now.

**Comment by jlebon** [comment] 2019-09-13 14:35
No strong opinion here on which org to move to, so `coreos/` SGTM if it provides real value in org/CI management. We can always move it again in the future if the winds of change blow us elsewhere.

**Comment by cgwalters** [comment] 2019-09-13 14:50
It is done: https://github.com/coreos/rpm-ostree

Closing this for now.

**Closed by cgwalters** 2019-09-13 14:50 UTC
Labels: kind/question
