### ISSUE TITLE
Ignition fails to mount /dev/disk/by-label/config-2

### ISSUE THREAD

**Issue by yuvalturg** [coreos/fedora-coreos-tracker#167] opened 2019-03-27 06:40 UTC
The openstack provider in ignition fails to mount /dev/disk/by-label/config-2 because it is missing on the disk - this is caused by a missing udev rule that imports CD information.  Creating a custom initramfs with the missing /lib/udev/rules.d/60-cdrom_id.rules fixes this.

**Comment by dustymabe** [comment] 2019-04-03 17:08
Looked at this when @yuvalturg reported it in IRC and confirmed that udev rule did not exist. I'm not super familiar with the openstack provider in ignition. @ajeddeloh  should this work with the openstack provider in ignition?

**Comment by bgilbert** [comment] 2019-04-03 17:09
@dustymabe It should.

**Comment by ajeddeloh** [comment] 2019-04-03 17:12
It should, the issue is just there's no udev rule to create the `/dev/disk/by-label/config-2` symlink. That udev rule should be supplied by systemd (at least it is on my gentoo system). We just need https://github.com/coreos/bootengine/blob/master/dracut/30ignition/module-setup.sh#L56

**Comment by yuvalturg** [comment] 2019-04-03 17:15
That's exactly the missing rule, after manually adding it to the initrd, everything worked fine :)

**Comment by ajeddeloh** [comment] 2019-04-03 17:31
https://github.com/coreos/ignition-dracut/pull/71 is up now, will backport to spec2x once that merges too

**Comment by rgolangh** [comment] 2019-04-08 06:42
Just to add more details here - @yuvalturg and I modified oVirt to pass ignition json through to cloud-init cdrom, config-2, and using the openstack ignition provider to ignite the OS. Thumbs up for the quick response guys. 
Where can I get the updated fedora images from?

**Comment by ajeddeloh** [comment] 2019-04-09 17:29
Looks like these are merged and included in new RPMs, closing.

**Closed by ajeddeloh** 2019-04-09 17:29 UTC

**Comment by ajeddeloh** [comment] 2019-04-09 17:30
I can't read. https://ci.centos.org/artifacts/fedora-coreos/prod/builds/latest/ is probably what you're looking for.
