### ISSUE TITLE
Emergency prompt doesnt show in VirtualBox

### ISSUE THREAD

**Issue by keithy** [coreos/fedora-coreos-tracker#353] opened 2020-01-24 21:52 UTC
When ignition fails the emercency prompt fails to show in VirtualBox.
Fixed this by removing the boot parameter "console=tty20,115200n8"

![Screen Shot 2020-01-24 at 21 35 55](https://user-images.githubusercontent.com/193501/73106609-b867b200-3ef3-11ea-92ca-8a6797315e85.jpg)

**Comment by bgilbert** [comment] 2020-01-24 21:55
Thanks for the report.  Note, though, that VirtualBox isn't supported yet.

**Comment by keithy** [comment] 2020-01-24 21:59
related? https://www.virtualbox.org/ticket/10396

**Comment by keithy** [comment] 2020-01-24 22:56
Related? https://forums.virtualbox.org/viewtopic.php?f=6&t=92832

**Comment by dustymabe** [comment] 2020-01-27 16:09
I think this is expected behavior. Unfortunately we have to choose whether VGA or Serial is the default console device (i.e. the last entry on the kernel command line). If you're using virtualbox via a "bare metal install" you should be able to set the `console=` device by using the `coreos-install install --firstboot-args=console=foo` option. I haven't tried this yet (been traveling). Let us know if it doesn't work.

**Comment by dustymabe** [comment] 2020-02-05 16:27
@keithy - any success here with my suggestion above?

**Comment by keithy** [comment] 2020-02-06 23:39
Unfortunately I do not think it works the extra "console=tty0" entry is prepended (being included after ignition.firstboot) and so does not have the desired effect. 

Manually appending it does work.

**Comment by dustymabe** [comment] 2020-02-07 15:22
cc @bgilbert ^^ do we have an ordering issue with `--firstboot-args` ? I would think they should be appended to the end

**Comment by dustymabe** [comment] 2020-02-07 15:44
hey @keithy - there is a possible fix for the ordering issue in https://github.com/coreos/coreos-assembler/pull/1109

**Comment by dustymabe** [comment] 2020-02-12 22:06
ok since https://github.com/coreos/coreos-assembler/pull/1109 landed to fix the issue with `--firstboot-args` and we just released new content I'm inclined to close this as "working as designed" for the reasons mentioned in https://github.com/coreos/fedora-coreos-tracker/issues/353#issuecomment-578821542. Perhaps if/when we add a virtualbox platform then we'll appropriately set the console for that platform to a sane default and we won't have this problem there.

**Closed by dustymabe** 2020-02-12 22:06 UTC
Labels: area/platforms, kind/question
