### ISSUE TITLE
kdump fails to start on arm64

### ISSUE THREAD

**Issue by jeffdyoung** [coreos/fedora-coreos-tracker#1529] opened 2023-07-18 15:29 UTC
### Describe the bug

Following these [steps](https://docs.fedoraproject.org/en-US/fedora-coreos/debugging-kernel-crashes/) to start kdump on arm64. The machine restarts, but kdump.service fail with this error:
```
Jul 18 14:44:21 ip-10-0-74-126 dracut[1198]: *** Squashing the files inside the initramfs ***
Jul 18 14:44:31 ip-10-0-74-126 dracut[1198]: *** Squashing the files inside the initramfs done ***
Jul 18 14:44:31 ip-10-0-74-126 dracut[1198]: *** Creating image file '/var/lib/kdump/initramfs-6.3.8-200.fc38.aarch64kdump.img' ***
Jul 18 14:44:31 ip-10-0-74-126 dracut[1198]: *** Creating initramfs image file '/var/lib/kdump/initramfs-6.3.8-200.fc38.aarch64kdump.img' done ***
Jul 18 14:44:32 ip-10-0-74-126 kdumpctl[4638]: sed: -e expression #1, char 14: unknown command: `/'
Jul 18 14:44:32 ip-10-0-74-126 kdumpctl[807]: kdump: kexec: failed to load kdump kernel
Jul 18 14:44:32 ip-10-0-74-126 kdumpctl[807]: kdump: Starting kdump: [FAILED]
```

### Reproduction steps

1. sudo rpm-ostree kargs --append='crashkernel=300M'
2. sudo systemctl enable kdump.service
3. sudo systemctl reboot
4. after the reboot check kdump.service

### Expected behavior

kdump.service should run, and a user should be able to generate a vmcore dump with `echo c > /proc/sysrq-trigger`

### Actual behavior

kdump fails to start.

### System details

- AWS ARM64 t4g.medium
- ami-03777816913e8e8a6

### Butane or Ignition config

```yaml
n/a, manually setup kdump
```

**Comment by dustymabe** [comment] 2023-09-08 02:43
Closing as a duplicate of https://github.com/coreos/fedora-coreos-tracker/issues/1430

**Closed by dustymabe** 2023-09-08 02:43 UTC
Labels: kind/bug
