### ISSUE TITLE
FCOS Live ISO fails to boot - "Unable to mount root filesystem"

### ISSUE THREAD

**Issue by cgruver** [coreos/fedora-coreos-tracker#555] opened 2020-06-27 12:23 UTC
FCOS Version: 32.20200601.3.0 "stable"

__Note:__ This works with FCOS version: 31.20200505.2.0 "testing"

I am doing something that might be a bit unusual...  I am using the live iso to bootstrap into an FCOS install from an ignition file for an OKD 4.4 Single Node Cluster.  https://github.com/cgruver/okd4-single-node-cluster

I suspect that one of the kernel parameters that I am using no longer works with newer FCOS versions.

I am creating a new iso from the live iso and replacing the `isolinux.cfg` with the following:

```
serial 0
default vesamenu.c32
timeout 1
display boot.msg
menu clear
menu separator
label linux
  menu label ^Fedora CoreOS (Live)
  menu default
  kernel /images/vmlinuz
  append initrd=/images/initramfs.img ip=10.11.11.49::10.11.11.1:255.255.255.0:okd4-snc-bootstrap.snc.test:eth0:none nameserver=10.11.11.209 rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=sda coreos.inst.image_url=http://10.11.11.209/install/fcos/install.xz coreos.inst.ignition_url=http://10.11.11.209/install/fcos/ignition/bootstrap.ign coreos.inst.platform_id=qemu console=ttyS0
menu separator
menu end
```

The VM is created as follows:

```
virt-install --name okd4-snc-bootstrap --memory 14336 --vcpus 2 --disk size=100,path=/VirtualMachines/okd4-snc-bootstrap/rootvol,bus=sata --cdrom /tmp/bootstrap.iso --network bridge=br0 --graphics none --noautoconsole --os-variant centos7.0
```

__This is the output at the beginning of the boot:__

```
Loading /images/initramfs.img...ok
[    0.000000] Linux version 5.6.14-300.fc32.x86_64 (mockbuild@bkernel03.phx2.fedoraproject.org) (gcc version 10.1.1 20200507 (Red Hat 10.1.1-1) (GCC)) #1 SMP Wed May 20 20:47:32 UTC 2020
[    0.000000] Command line: BOOT_IMAGE=/images/vmlinuz initrd=/images/initramfs.img ip=10.11.11.49::10.11.11.1:255.255.255.0:okd4-snc-bootstrap.snc.test:eth0:none nameserver=10.11.11.209 rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=sda coreos.inst.image_url=http://10.11.11.209/install/fcos/install.xz coreos.inst.ignition_url=http://10.11.11.209/install/fcos/ignition/bootstrap.ign coreos.inst.platform_id=qemu console=ttyS0
```

__This is the error before it enters maintenance mode:__

```
[  OK  ] Reached target Initrd Default Target.
         Startin[    3.892993] systemd[1]: Starting dracut mount hook...
g dracut mount hook...
[    3.997827] dracut-mount[627]: Warning: Can't mount root filesystem
[    3.773644] dracut-mount[627]: Warning: Can't mount root filesystem
[  OK  ] Stopped target Init[    4.012207] systemd[1]: Stopped target Initrd Default Target.
rd Default Target.
[  OK      4.015885] systemd[1]: Stopped target Subsequent (Not Ignition) boot complete.
0m] Stopped target Subsequent (Not Ignition) boot complete.
         Starting Dracut Emergency Shell...
[    4.026850] systemd[1]: Starting Dracut Emergency Shell...
```

**Comment by cgwalters** [comment] 2020-06-27 12:42
> am creating a new iso from the live iso and replacing the isolinux.cfg with the following:

Why?  To configure networking?  Instead, inject the network config as NetworkManager config fragments.  Then you don't need to edit the ISO.  And better, those config fragments will by default be propagated into your target system.

(The reason it's failing is you're missing `coreos.liveiso=`, but rather than re-adding that please use Ignition to configure the ISO)

**Comment by cgwalters** [comment] 2020-06-27 12:44
> I am doing something that might be a bit unusual... I am using the live iso to bootstrap into an FCOS install from an ignition file for an OKD 4.4 Single Node Cluster. 

That's not unusual!  For OpenShift 4 (the product) we are [building significant tooling](https://github.com/openshift/enhancements/pull/376) on top of the Live ISO, and currently all of that is just Ignition.

**Comment by cgruver** [comment] 2020-06-27 13:12
@cgwalters 

Thanks for the tips.  I'll try some different approaches.

Is there a tutorial or something that you can link me to for creating the NetworkManager config fragments?  I have not created custom ignition configs before.

I'm using the method described above so that it is executed from a shell script.  It is to avoid having to modify the ignition files generated by openshift-install.  This is effectively mimicking a PXE install, without requiring the user to set up a PXE server.

I'm trying to keep a single node cluster install as simple as possible for folks new to OKD 4.  At least until we get CRC working for OKD.

Thanks!

**Comment by cgwalters** [comment] 2020-06-27 13:29
See https://github.com/dustymabe/dustymabe.com/blob/master/content/post/2020-04-04/post.md

**Comment by cgwalters** [comment] 2020-06-27 13:31
And to clarify, you should take the Ignition config generated by `openshift-install` and pass it to `coreos-install`; it's a distinct configuration from that provided for the Live ISO.  In other words the openshift-install generated Ignition ends up embedded as a regular file (data) inside the Ignition provided to the ISO.

**Comment by lucab** [comment] 2020-07-01 12:04
> I am creating a new iso from the live iso and replacing [...]

Closing at this boot failure is not a bug affecting FCOS live-ISO artifacts.

**Closed by lucab** 2020-07-01 12:04 UTC
