### ISSUE TITLE
Separate /var mount breaks writable /etc

### ISSUE THREAD

**Issue by msoranno** [coreos/fedora-coreos-tracker#617] opened 2020-09-03 10:58 UTC
Hello, thanks for reading this.

# The situation
- comming from `31.20200420.3.0` and FCC file version `1.0.0` qemu image where everything works just fine.
- After changing to `32.20200809.3.0` and FCC file version to `1.1.1` the qemu machine starts bu with no openssh server.
- for some reason /etc is read-only

# Login ok but , but /etc on read-only
```
[msoranno@localhost ~]$ sudo ssh-keygen -A
ssh-keygen: generating new host keys: RSA Could not save your private key in /etc/ssh/ssh_host_rsa_key.PQ3WVrYsVU: Read-only file system
ssh-keygen: generating new host keys: DSA Could not save your private key in /etc/ssh/ssh_host_dsa_key.UkRIzddDPW: Read-only file system
ssh-keygen: generating new host keys: ECDSA Could not save your private key in /etc/ssh/ssh_host_ecdsa_key.pcu4hDoTce: Read-only file system
ssh-keygen: generating new host keys: ED25519 Could not save your private key in /etc/ssh/ssh_host_ed25519_key.3lIJxb8hj0: Read-only file system
```
# some logs of the sshd service
```
Sep 03 10:46:55 localhost systemd[1]: Failed to start OpenSSH server daemon.
Sep 03 10:47:38 localhost systemd[1]: sshd.service: Scheduled restart job, restart counter is at 37.
Sep 03 10:47:38 localhost systemd[1]: Stopped OpenSSH server daemon.
Sep 03 10:47:42 localhost systemd[1]: Starting OpenSSH server daemon...
Sep 03 10:47:42 localhost sshd[5058]: sshd: no hostkeys available -- exiting.
Sep 03 10:47:42 localhost systemd[1]: sshd.service: Main process exited, code=exited, status=1/FAILURE
Sep 03 10:47:42 localhost systemd[1]: sshd.service: Failed with result 'exit-code'.
Sep 03 10:47:42 localhost systemd[1]: Failed to start OpenSSH server daemon.
Sep 03 10:48:24 localhost systemd[1]: sshd.service: Scheduled restart job, restart counter is at 38.
Sep 03 10:48:24 localhost systemd[1]: Stopped OpenSSH server daemon.
Sep 03 10:48:31 localhost systemd[1]: Starting OpenSSH server daemon...
Sep 03 10:48:32 localhost sshd[5071]: sshd: no hostkeys available -- exiting.
Sep 03 10:48:32 localhost systemd[1]: sshd.service: Main process exited, code=exited, status=1/FAILURE
Sep 03 10:48:32 localhost systemd[1]: sshd.service: Failed with result 'exit-code'.
Sep 03 10:48:32 localhost systemd[1]: Failed to start OpenSSH server daemon.
Sep 03 10:49:14 localhost systemd[1]: sshd.service: Scheduled restart job, restart counter is at 39.
Sep 03 10:49:14 localhost systemd[1]: Stopped OpenSSH server daemon.
Sep 03 10:49:28 localhost systemd[1]: Starting OpenSSH server daemon...
Sep 03 10:49:28 localhost sshd[5344]: sshd: no hostkeys available -- exiting.
Sep 03 10:49:28 localhost systemd[1]: sshd.service: Main process exited, code=exited, status=1/FAILURE
Sep 03 10:49:28 localhost systemd[1]: sshd.service: Failed with result 'exit-code'.
Sep 03 10:49:28 localhost systemd[1]: Failed to start OpenSSH server daemon.
Sep 03 10:50:10 localhost systemd[1]: sshd.service: Scheduled restart job, restart counter is at 40.
Sep 03 10:50:10 localhost systemd[1]: Stopped OpenSSH server daemon.
Sep 03 10:50:13 localhost systemd[1]: Starting OpenSSH server daemon...
Sep 03 10:50:13 localhost sshd[5406]: sshd: no hostkeys available -- exiting.
Sep 03 10:50:13 localhost systemd[1]: sshd.service: Main process exited, code=exited, status=1/FAILURE
Sep 03 10:50:13 localhost systemd[1]: sshd.service: Failed with result 'exit-code'.
Sep 03 10:50:13 localhost systemd[1]: Failed to start OpenSSH server daemon.
```
# rpm-ostree status
```
[msoranno@localhost ~]$ sudo rpm-ostree status
State: idle
Deployments:
● ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 32.20200809.3.0 (2020-08-24T16:27:55Z)
                    Commit: 902c88022e834fb7998140734fae01b75f78b80f63364e9c5309d62d9a260b7c
              GPGSignature: Valid signature by 97A1AE57C3A2372CCA3A4ABA6C13026D12C944D0

```

# starting qemu like this - Running on a VM with Ubuntu 18

```
qemu-system-x86_64 -name fedora_coreos_production_qemu -netdev user,id=eth0,hostfwd=tcp::2222-:22,hostname=fedora_coreos_production_qemu -fw_cfg name=opt/com.coreos/config,file=bastion-ignition.ign -drive if=virtio,file=./fedora-coreos-32.20200809.3.0-qemu.x86_64.qcow2 -machine accel=tcg -m 4096 -smp 4 -nographic
```

# My fcc file
```
variant: fcos
version: 1.1.0
passwd:
  users:
   # Note: password hash generated like:
   # echo 'mypass' | openssl passwd -1 -stdin
    - name: core
      ssh_authorized_keys:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAA.... core@bastion"
storage:
    # This partition will be mounted on the systemd below.
  disks:
    -
      device: /dev/vda # For qemu is vda , but when vmware will be auto transform in sda
      wipe_table: false
      partitions:
      - size_mib: 0  
        start_mib: 0
        label: var
  filesystems:
    - path: /var
      device: /dev/disk/by-partlabel/var
      format: xfs
  directories:
    - path: /var/bastionboot
      overwrite: true
      mode: 0755
  files:
    # This will lower down the log level sended to kmsg. This is in order to avoid spam 
    # Also disable ipv6
    - path: /etc/sysctl.conf
      overwrite: true
      mode: 0644
      contents:
        inline: |
          kernel.printk=4
          # net.ipv6.conf.all.disable_ipv6=1
          # net.ipv6.conf.default.disable_ipv6=1
          # net.ipv6.conf.lo.disable_ipv6=1

systemd:
  units:
    -
      # We need to create a systemd mount unit so that /var actually gets
      # mounted on /var.
      name: var.mount
      enabled: true
      contents: |
        [Unit]
        Before=local-fs.target
        [Mount]
        Where=/var
        What=/dev/disk/by-partlabel/var
        [Install]
        WantedBy=local-fs.target  
```

# compiler version
```
fcct-x86_64-unknown-linux-gnu --version
Fedora CoreOS Config Transpiler 0.6.0

```

**Comment by lucab** [comment] 2020-09-03 11:39
Thanks for the report. This looks like a regression related to how the additional `/var` mountpoint is handled.
Dropping the filesystem entry and the mount unit from your config makes the machine boot normally.

From a quick look however I'm unsure what's going wrong. I can see that `/var` is mounted from the custom partition and `rw` in both cases, so there is likely something a bit more tricky going on.

**Comment by msoranno** [comment] 2020-09-03 11:49
Thanks @lucab , please let me know is anything i can do to help solve this situation.

**Comment by lucab** [comment] 2020-09-03 12:51
@msoranno not really, some bug slipped in and caused a regression in this specific usecase. Until figured out, I think the only workaround right now is not to use a separate `/var` mount.
If you are only caring about a specific directory in that hierarchy (e.g. `/var/lib/containers`) you may try setting that up instead.

**Comment by msoranno** [comment] 2020-09-03 13:24
@lucab no worries, we will keep using `31.20200420.3.0` until it is solved... Thanks

**Comment by dustymabe** [comment] 2020-09-03 15:36
@msoranno - some more information that would be useful is to try with older versions (browse [here](https://builds.coreos.fedoraproject.org/browser?stream=stable)) and let us know what was the last version it worked in.

**Comment by msoranno** [comment] 2020-09-03 16:04
@dustymabe i will try this one tomorrow and let you know: https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/32.20200629.3.0/x86_64/fedora-coreos-32.20200629.3.0-qemu.x86_64.qcow2.xz

**Comment by cgwalters** [comment] 2020-09-03 16:52
Yeah this is bad, we have a pending ostree fix in https://github.com/ostreedev/ostree/pull/2186

We should probably hold upgrade rollouts until we have that patched.

**Comment by cgwalters** [comment] 2020-09-03 18:01
Could use a lgtm on https://github.com/ostreedev/ostree/pull/2189

**Comment by cgwalters** [comment] 2020-09-03 18:01
I validated that it works with the added tests in https://github.com/coreos/fedora-coreos-config/pull/586

**Comment by cgwalters** [comment] 2020-09-03 19:21
https://bodhi.fedoraproject.org/updates/FEDORA-2020-eb29bce63d should fix this.

**Comment by dustymabe** [comment] 2020-09-03 19:43
Thanks Colin!

**Comment by dustymabe** [comment] 2020-09-03 20:22
> https://bodhi.fedoraproject.org/updates/FEDORA-2020-eb29bce63d should fix this.

Added it as an override in https://github.com/coreos/fedora-coreos-config/pull/596

**Comment by dustymabe** [comment] 2020-09-03 20:28
> > https://bodhi.fedoraproject.org/updates/FEDORA-2020-eb29bce63d should fix this.
> 
> Added it as an override in [coreos/fedora-coreos-config#596](https://github.com/coreos/fedora-coreos-config/pull/596)

And https://github.com/coreos/fedora-coreos-config/pull/597 (for `next-devel`).

**Comment by lucab** [comment] 2020-09-04 14:01
From an out-of-band conversation: the problematic bump is `ostree 2020.3-5.fc32.x86_64 → 2020.4-4.fc32.x86_64`.

It may be worth to pause the latest rollout on `stable` (even if it already reached 100% at this point). On both `testing` and `next` though the `2020.4` version has already been shipped in at least the two latest releases, so there is probably little value in pausing those.

**Comment by dustymabe** [comment] 2020-09-04 15:16
> It may be worth pausing the latest rollout on `stable` (even if it already reached 100% at this point).

Existing systems should probably be updated already (if auto updates enabled). So the value here would be make sure we don't break newly provisioned systems that start from an older release?

A larger question is do we want to fast track this so we can get it to stable sooner. I think we should probably have an ad-hoc `testing` release with just an updated `ostree` and then slightly delay next week's planned `stable` to later in the week.

**Comment by dustymabe** [comment] 2020-09-04 19:58
The fix for this went into testing stream release `32.20200824.2.1`. Please try out the new release and report issues.

**Closed** 2020-09-05 20:15 UTC
Labels: component/ostree, kind/regression, needs/investigation, status/pending-stable-release

**Comment by dustymabe** [comment] 2020-09-09 03:09
The fix for this went into stable stream release `32.20200824.3.0`. Please try out the new release and report issues.
