### ISSUE TITLE
Document how to disable autoconfiguration of network interfaces

### ISSUE THREAD

**Issue by lkundrak** [coreos/fedora-coreos-tracker#227] opened 2019-07-24 14:18 UTC
The default NetworkManager configuration (generating default connection on seeing a carrier) is intended for desktops. Server administrators don't tend to appreciate devices getting brought up without anyone asking.

**Comment by lucab** [comment] 2019-07-24 14:34
For reference, the `NetworkManager-config-server` adds this configuration file: https://src.fedoraproject.org/rpms/NetworkManager/blob/master/f/00-server.conf

**Comment by cgwalters** [comment] 2019-07-24 14:43
The problem is that "server" here is really more "bare metal server" - in cloud environments we really do want to do DHCP by default.

**Comment by cgwalters** [comment] 2019-07-24 14:53
Maybe we could do this conditionally based on the Ignition platform id but...

1) In practice RHCOS already shipped with DHCP by default, and having FCOS diverge would be messy
2) Anyone who wants to turn off DHCP for bare metal can do so by e.g. writing Ignition which sets this file - something we could consider making more ergonomic

**Comment by bgilbert** [comment] 2019-07-24 18:01
Fedora CoreOS is intended to require zero network configuration in environments that support that, including on bare metal, so we intentionally autoconfigure active interfaces.  We should document how to change that behavior, though.

(For reference, Container Linux has always worked this way.)

**Comment by dustymabe** [comment] 2022-04-14 14:21
Thanks @mohelt for picking this one up.

**Comment by dustymabe** [comment] 2022-05-10 12:43
Fixed in https://github.com/coreos/fedora-coreos-docs/pull/402

**Closed by dustymabe** 2022-05-10 12:43 UTC
Labels: jira, area/docs, component/NetworkManager
