### ISSUE TITLE
Latest next VMWare OVA Fails To Boot

### ISSUE THREAD

**Issue by fifofonix** [coreos/fedora-coreos-tracker#1802] opened 2024-09-24 14:01 UTC
### Describe the bug

When launching a sans ignition Fedora41 `next` OVA in VMWare Workstation on Windows the VM fails to boot with the message "The firmware encountered an unexpected exception. The vfirtual machine cannot boot." When using the `testing` Fedora40 OVA the VM boots to a login prompt without issue.

Separately, CICD scripts that deploy the same OVAs using OpenTofu to a server VMWare vSphere infrastructure, also fail although without such a message. In the server deployment case the VMs will be listed in vSphere but will be in an 'off' status, with any power on attempts yielding an 'off' status. No console messages produced or error messages. Again the same projects using `testing` deploy just fine.

### Reproduction steps

1. Download OVA
2. Attempt to launch via VMWare Workstation

### Expected behavior

VM should boot to login as it does for prior FCOS versions

### Actual behavior

As described above.

### System details

- VMWare Workstation or VMWare vSphere

### Butane or Ignition config

```yaml
None
```

### Additional information

![image](https://github.com/user-attachments/assets/d7e18075-2049-4e5e-918f-ae571f1d1f07)

**Comment by dustymabe** [comment] 2024-09-24 19:03
so there's no messages at all on the console of the VMWare machines? Does the VM even attempt to boot at all or is it something happening at the VMware level that is causing it to not work at all?

What happens if you boot a `testing` machine, but [rebase it](https://docs.fedoraproject.org/en-US/fedora-coreos/update-streams/#_switching_to_a_different_stream) to `next`?

**Comment by fifofonix** [comment] 2024-09-25 19:23
No console/boot messages at all so it seems like there is something wrong with the OVA.

To all intents and purposes the VM in vSphere looks the same as a `testing` one, ie. same vmware virtual machine version #.

Rebasing a `testing` machine to `next` works fine.

Also, I have re-confirmed today that the OVA deployment issue exists with the very latest `next`, ie. 41.20240922.1.0.

**Comment by dustymabe** [comment] 2024-09-25 20:13
> Also, I have re-confirmed today that the OVA deployment issue exists with the very latest `next`, ie. 41.20240922.1.0.

Can you also confirm it DOES NOT exist with the lastest `testing`: `40.20240920.2.0` ?

**Comment by fifofonix** [comment] 2024-09-26 14:29
Confirmed. Overnight `testing` CICD deployed canary VM without issues.

**Comment by dustymabe** [comment] 2024-09-26 15:15
We use the exact same build container to build `testing` and `next` so there should be no difference in how the OVA is constructed. That would indicate to me there is a problem inside the OS (i.e. kernel, grub, or something), but rebasing from `testing` to `next` would test that theory and you said that rebasing works too.

I'm really not sure. I would expect something to come across the console that we could use to investigate, but you say there is nothing there either :(

**Comment by dustymabe** [comment] 2024-09-26 15:19
> That would indicate to me there is a problem inside the OS (i.e. kernel, grub, or something), but rebasing from `testing` to `next` would test that theory and you said that rebasing works too.

ahh. rebasing from `testing` to `next` wouldn't update the bootloader that's installed.

Can you run `sudo bootupctl update` on that rebased system and then reboot to see if it then fails to boot?

**Comment by fifofonix** [comment] 2024-09-26 20:14
This replicate the issue with the node failing to reboot and failing to reboot when manual power on signal is given via vSphere console. For the record this was the output I got when applying `bootupctl update`. Hopefully, this means you can narrow in on what the issue is?

```
me@t-canary-vm:~$ sudo bootupctl update
Running as unit: bootupd.service
Previous BIOS: grub2-tools-1:2.06-123.fc40.x86_64
Updated BIOS: grub2-tools-1:2.12-4.fc41.x86_64
Previous EFI: grub2-efi-x64-1:2.06-123.fc40.x86_64,shim-x64-15.8-3.x86_64
Updated EFI: grub2-efi-x64-1:2.12-4.fc41.x86_64,shim-x64-15.8-3.x86_64
```

**Comment by hrismarin** [comment] 2024-10-01 07:32
> Is there a way you could try the "bare metal install" workflow using our ISO image (or PXE)?

At least on my side bare metal install using ISO image works.

```
$ sudo rpm-ostree status 
State: idle
AutomaticUpdatesDriver: Zincati
  DriverState: active; periodically polling for updates (last checked Tue 2024-10-01 07:18:06 UTC)
Deployments:
● fedora:fedora/x86_64/coreos/next
                  Version: 41.20240922.1.0 (2024-09-23T17:19:23Z)
                   Commit: 9193342bf66c4b38fbf49d1d59af8a4e3f0c8ca4cb9d674ad3ba9713eea798c9
             GPGSignature: Valid signature by 466CF2D8B60BC3057AA9453ED0622462E99D6AD1
```

**Comment by dustymabe** [comment] 2024-10-01 14:04
> At least on my side bare metal install using ISO image works.

Are you on VMWare?

**Comment by fifofonix** [comment] 2024-10-01 18:35
Booting the aarch64 live ISO on VMWare Fusion shows the Grub prompt and goes through to the live bash prompt. Is this sufficient to prove that Grub is not the issue or do I need to install to disk to complete this test?

Note this is slightly different to the original issue which is reported for x86. Do I need to find an old Mac to test the x86 live ISO too?

**Comment by dustymabe** [comment] 2024-10-01 18:45
> Booting the aarch64 live ISO on VMWare Fusion shows the Grub prompt and goes through to the live bash prompt. Is this sufficient to prove that Grub is not the issue or do I need to install to disk to complete this test?
> 
> Note this is slightly different to the original issue which is reported for x86. Do I need to find an old Mac to test the x86 live ISO too?

Yeah - not switching out the architecture would be nice. Sorry I just thought you had a VMWare infra (other than your laptop) where you could run a test. It would be nice if we could try the test on the same architecture and same infra where you hit the original failures. I think that would be on x86_64, and yes, preferrably a full install to disk + reboot.

**Comment by fifofonix** [comment] 2024-10-01 19:26
Had a colleague run the x86 ISO and install to disk on VMWare Workstation and everything goes well. This is an environment that fails when you try to install the OVA.

**Comment by hrismarin** [comment] 2024-10-01 20:10
> Are you on VMWare?

Yes, I installed Windows 10 on a bare machine, installed VMWare Workstation 17 Player and then installed Fedora CoreOS `next` from the ISO. I haven't tried installing the OVA yet. Shall I try?

**Comment by dustymabe** [comment] 2024-10-01 20:30
> > Are you on VMWare?
> 
> Yes, I installed Windows 10 on a bare metal machine, installed VMWare Workstation 17 Player and then installed Fedora CoreOS `next` from the ISO.


Awesome. Thanks!

> I haven't tried installing the OVA yet. Shall I try?

If you have time that would be great! More datapoints certainly help!

**Comment by dustymabe** [comment] 2024-10-01 20:31
> Had a colleague run the x86 ISO and install to disk and reboot on VMWare Workstation and everything goes well. This is an environment that fails when you try to install the OVA.

Thanks! This should help us narrow down the root cause. I'm guessing now somehow some issue in how the OVA is built for one versus the other. Though it is the same code that is currently building `testing` and `next` so I'm not sure what the difference could be.

**Comment by hrismarin** [comment] 2024-10-01 21:45
I can confirm that when I try to boot the `next` OVA image in VMWare Workstation on Windows, the issue is reproduced with the same error message from the bug description.

**Comment by gursewak1997** [comment] 2024-10-02 16:58
From the community meeting:
@ravanelli will help dig this down and diagnose the issue further to find the root cause.

**Comment by ravanelli** [comment] 2024-10-02 20:27
Just adding thoughts here, the only thing that changed at our side was the osbuild part, maybe something before the OVA creation could be causing it?

**Comment by dustymabe** [comment] 2024-10-03 12:57
> As a summary, we are guessing here the issue is around in how the OVA image is created and not around an issue in Grub?

According to the reported test results above it seems like it could be either. There's definitely something nuanced here. 

> I will try to create an image with fcos#41-next downgrading the grub to see what it gives us.

That will be a good test.

**Comment by ravanelli** [comment] 2024-10-03 14:09
it is indeed a grub issue?
 Downgrade to `2.06.124.fc41` works
 Upgrade it to `2.12-7.fc42` got the same issue.

**Comment by travier** [comment] 2024-10-03 14:30
Can you try https://bodhi.fedoraproject.org/updates/FEDORA-2024-a067416d33 ? That should narrow it to the 2.12 rebase.

**Comment by ravanelli** [comment] 2024-10-03 15:23
> Can you try https://bodhi.fedoraproject.org/updates/FEDORA-2024-a067416d33 ? That should narrow it to the 2.12 rebase.

Same issue, won't boot.

**Comment by ravanelli** [comment] 2024-10-07 19:54
Fedora BZ opened: https://bugzilla.redhat.com/show_bug.cgi?id=2317048

**Comment by ravanelli** [comment] 2024-10-08 02:12
I added the options `pager=0` and `debug=all` in the grub.cfg as suggested by Marta Lewandowska, still nothing shows up in VMware, it is failing even before it.

**Comment by dustymabe** [comment] 2024-10-08 13:10
Two more data points that might be helpful:

- @fifofonix since you have a aarch64 Mac, can you test the OVA (not the ISO), does it work? our aarch64 images are UEFI only, so that may help us narrow down the cause.
- @ravanelli is there a way to boot a machine on your x86 Mac with UEFI vs BIOS? We know at least one of them fails. Do both of them fail?

**Comment by ozbenh** [comment] 2024-10-15 22:05
This is confusing as "serial" isn't supposed to be used with UEFI (you should be using the UEFI console...)

**Comment by ozbenh** [comment] 2024-10-16 05:08
I found the bug in grub ACPI code, fix attached to the above RH bugzilla and will be on its way upstream soon

**Comment by dustymabe** [comment] 2024-10-16 15:37
Thanks so much @ozbenh!

@marta-lewandowska - could we get https://lists.gnu.org/archive/html/grub-devel/2024-10/msg00216.html backported to rawhide and Fedora 41?

**Comment by marta-lewandowska** [comment] 2024-10-17 06:56
> Thanks so much @ozbenh!
> 
> @marta-lewandowska - could we get https://lists.gnu.org/archive/html/grub-devel/2024-10/msg00216.html backported to rawhide and Fedora 41?

we're working on it. looks like upstream reviewed the patch, so we should be able to take it as is.

**Comment by dustymabe** [comment] 2024-10-17 14:05
new package fast-track in https://github.com/coreos/fedora-coreos-config/pull/3190

**Comment by dustymabe** [comment] 2024-10-17 19:58
fixup in https://github.com/coreos/fedora-coreos-config/pull/3209

**Comment by hrismarin** [comment] 2024-10-18 08:54
`fedora-coreos-41.20241017.10.0-vmware.x86_64.ova` build works on VMware Player 17.6.1 (Windows 10).

**Comment by HuijingHei** [comment] 2024-10-18 15:12
Also did testing `fedora-coreos-41.20241017.10.0-vmware.x86_64.ova` on ESXi, VM can start successfully.

**Comment by ravanelli** [comment] 2024-10-18 18:28
Tested in Mac X86, with security boot, also worked fine!

**Comment by fifofonix** [comment] 2024-10-23 13:40
This morning our daily scheduled pipelines for the deployment of `next` canary nodes to VMWare vSphere succeeded. Yay!

**Comment by dustymabe** [comment] 2024-10-28 19:40
The fix for this went into `next` stream release `41.20241020.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment] 2024-10-28 19:40
This issue never affected `testing` or `stable` streams.

**Closed by dustymabe** 2024-10-28 19:40 UTC
Labels: kind/bug, jira, status/pending-next-release, F41, fallout/f41
