### ISSUE TITLE
`coreos-boot-edit.sh` creates `/boot/.root_uuid` as `unlabeled_t`

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-tracker#1770] opened 2024-07-31 10:39 UTC
### Describe the bug

https://github.com/coreos/fedora-coreos-config/blob/testing-devel/overlay.d/05core/usr/lib/dracut/modules.d/35coreos-ignition/coreos-boot-edit.sh likely runs before we've loaded the SELinux policy and writes `/boot/.root_uuid` which ends up not being labeled (`unlabeled_t`).

### Reproduction steps

Boot FCOS. Run:

```
ls -alhZ /boot
```

### Expected behavior

All files are correctly labeled.

### Actual behavior

`/boot/.root_uuid` is `unlabeled_t`.

### System details

N/A

### Butane or Ignition config

```yaml
None
```

**Comment by jlebon** [comment] 2024-08-06 20:29
A `coreos-relabel` would fix it for new systems, but I think that'd require changing `coreos-boot-edit` to actually do the temporary boot mount under `/sysroot/boot` instead of `/mnt/boot_partition` so the expected path lines up. (Though there's a bit of a layering violation in that the script would have to know that `rdcore bind-boot` writes that file; `rdcore` could itself call `coreos-relabel` instead, but that command so far hasn't really escaped this repo.)

We should probably fix it on existing systems, but it doesn't seem worth a barrier. We could bundle it in whatever the next barrier release we do.

**Comment by dustymabe** [comment] 2024-09-05 19:58
> We should probably fix it on existing systems, but it doesn't seem worth a barrier. We could bundle it in whatever the next barrier release we do.

@jbtrystram is working on a migration script to fixup labels on systems for https://github.com/coreos/fedora-coreos-tracker/issues/1771 and various other issues so we can fix these too.

We kind of need all of these root causes of the unlabeled files fixed too before we can release the migration script (i.e. freshly installed systems at a certain point should have no `unlabeled_t` once installed).

What's the proper fix for this root cause?

**Comment by dustymabe** [comment] 2024-09-30 12:51
https://github.com/coreos/fedora-coreos-config/pull/3150/commits/8d75174faf045c2342c34b5be209ca07677b4f09 fixes this for upgrading systems too.

**Closed** 2024-09-30 12:52 UTC
Labels: kind/bug, jira, area/selinux, status/pending-testing-release, status/pending-next-release

**Comment by dustymabe** [comment] 2024-10-18 20:42
The fix for this went into `next` stream release `41.20241006.1.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment] 2024-10-18 20:42
The fix for this went into `testing` stream release `40.20241006.2.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment] 2024-10-28 19:47
The fix for this went into `stable` stream release `40.20241006.3.0`.
