### ISSUE TITLE
Requesting ` systemd-journal-remote` package in Fedora CoreOS

### ISSUE THREAD

**Issue by pampelmuse76** [coreos/fedora-coreos-tracker#1414] opened 2023-02-13 08:49 UTC
I would like to collect all logs from my coreos instances on a central server for analyses/monitoring.
But I cannot find a good way to send (journal) logs to a remote server.
What about to add the systemd service "systemd-journal-upload" to coreos?
Thanks

**Comment by dustymabe** [comment] 2023-02-13 15:07
Once you have filled out the template add the `meeting` label to the ticket and we'll discuss it at our weekly community meeting.

**Comment by travier** [comment] 2023-04-12 17:33
Closing as a duplicate of https://github.com/coreos/fedora-coreos-tracker/issues/1415

**Closed by travier** 2023-04-12 17:33 UTC
