### ISSUE TITLE
fedora-coreos image for openstack is not usable

### ISSUE THREAD

**Issue by gthiemonge** [coreos/fedora-coreos-tracker#327] opened 2019-12-13 15:19 UTC
I downloaded the fedora-coreos image for openstack from https://getfedora.org/en/coreos/download/

The image (https://builds.coreos.fedoraproject.org/prod/streams/testing/builds/31.20191211.1/x86_64/fedora-coreos-31.20191211.1-openstack.x86_64.qcow2.xz) is invalid because it should be used with a backing file that is not provided:

```
$ file fedora-coreos-31.20191211.1-openstack.x86_64.qcow2 
fedora-coreos-31.20191211.1-openstack.x86_64.qcow2: QEMU QCOW2 Image (v3), has backing file (path /home/jenkins/workspace/fedora-coreos/fedora-coreos-fedora-coreos-pipeline/builds/31.20191211.1), 8589934592 bytes
```

**Comment by cgwalters** [comment] 2019-12-13 15:21
Ohh gah, this is likely a regression from https://github.com/coreos/coreos-assembler/pull/935

**Comment by cgwalters** [comment] 2019-12-13 15:25
PR in https://github.com/coreos/coreos-assembler/pull/999

**Comment by jlebon** [comment] 2019-12-13 15:50
Yes, the image for that platform is borked, as well as Alibaba since it's also a pure `gf-platformid`'ed qcow2. The other cloud images should be fine since they're converted into other formats.

A workaround for this is to simply provision from the previous version for now and letting the system auto-update to the latest release.

**Comment by dustymabe** [comment] 2019-12-13 15:51
Thanks for the report @gthiemonge!

**Comment by dustymabe** [comment] 2019-12-13 15:53
> A workaround for this is to simply provision from the previous version for now and letting the system auto-update to the latest release.

here is a link to the previous version: https://builds.coreos.fedoraproject.org/prod/streams/testing/builds/31.20191127.1/x86_64/fedora-coreos-31.20191127.1-openstack.x86_64.qcow2.xz

**Comment by dustymabe** [comment] 2019-12-13 15:57
Actually I think that one has the problem too, so you'll have to go back to https://builds.coreos.fedoraproject.org/prod/streams/testing/builds/30.20191014.1/x86_64/fedora-coreos-30.20191014.1-qemu.x86_64.qcow2.xz

**Comment by gthiemonge** [comment] 2019-12-13 16:05
thanks for the quick replies/fix!

**Comment by lucab** [comment] 2019-12-16 10:09
Let's keep this open until we tag the next release on `testing` stream, which should hopefully bring back working bootimages for openstack and aliyun.

**Comment by brtknr** [comment] 2019-12-19 00:21
I tried this openstack image today and it appears to be working again: https://builds.coreos.fedoraproject.org/prod/streams/testing/builds/31.20191217.2.0/x86_64/fedora-coreos-31.20191217.2.0-openstack.x86_64.qcow2.xz

**Comment by lucab** [comment] 2019-12-19 09:43
@brtknr thanks for the feedback. The `31.20191217.2.0` release is still in progress at https://github.com/coreos/fedora-coreos-streams/issues/38. Once completed, it will also show up on the download page. We'll close this bug too at that time.

**Comment by lucab** [comment] 2019-12-19 14:48
Fixed on the `testing` stream in release `31.20191217.2.0`.

**Closed by lucab** 2019-12-19 14:48 UTC
Labels: kind/regression, platform/openstack

**Comment by jmutai** [comment] 2020-01-26 20:42
Instance creation guide; https://computingforgeeks.com/install-fedora-coreos-fcos-on-kvm-openstack/

**Comment by lucab** [comment] 2020-01-27 09:22
@jmutai for reference, it would be helpful not to hardcode OS versions in URLs, and to verify images before using them.
`coreos-installer` can do that for you (and more). See `coreos-installer download --help` for more details.

**Comment by jmutai** [comment] 2020-01-27 18:45
@lucab Thanks for the comment. This has been fixed.
