### ISSUE TITLE
check-diff GitHub action failing in multiple repos

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1831] opened 2024-11-12 20:36 UTC
This is failing in `fedora-coreos-config` and `fedora-coreos-streams`. We need to figure out what is going on and get it fixed:

- https://github.com/coreos/fedora-coreos-streams/pull/980
- https://github.com/coreos/fedora-coreos-config/pull/3251

```
Run coreos/actions-lib/check-diff@main
/usr/bin/docker run --name a86d1ab0e5b7c4d41a8809ee5e5c00422cb_3616d6 --label 437a86 --workdir /github/workspace --rm -e "INPUT_BASEDIR" -e "INPUT_PATCHDIR" -e "INPUT_PATH" -e "INPUT_SEVERITY" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/fedora-coreos-streams/fedora-coreos-streams":"/github/workspace" 437a86:d1ab0e5b7c4d41a8809ee5e5c00422cb  "old" "new" "." "--severity" "warning"
exec /usr/bin/check-diff: no such file or directory
```

**Comment by stephankoelle** [comment] 2024-11-13 09:43
for me the problem is:  -v "/var/run/docker.sock":"/var/run/docker.sock"

**Comment by aaradhak** [comment] 2024-11-22 21:33
I merged the actions-lib [PR](https://github.com/coreos/actions-lib/pull/12) and tested the github action working here - https://github.com/coreos/fedora-coreos-config/pull/3262 . The checkdiff Github action is green. 

The issue seems to be that python pkg is missing in Fedora 41. By installing python in the Dockerfile, the checkdiff action seem to work.

**Comment by aaradhak** [comment] 2024-11-22 22:06
I think this issue can be closed now

**Closed by aaradhak** 2024-11-22 22:06 UTC
Labels: jira
