### ISSUE TITLE
Allow zip as a compression method

### ISSUE THREAD

**Issue by nsmith5** [coreos/fedora-coreos-tracker#721] opened 2021-01-21 18:09 UTC
**Describe the enhancement**
zip compression would make it easy to install tools like nomad (packaged with zip from upstream). Ideally I'd like something like

```
files:
  - path: /usr/bin/nomad
    mode: 0644
    contents:
      compression: zip
      source: https://releases.hashicorp.com/nomad/0.11.8/nomad_0.11.8_linux_amd64.zip
```

to work.

**Comment by jlebon** [comment] 2021-01-21 19:02
This looks like a dupe of https://github.com/coreos/ignition/issues/867. If possible, let's keep discussions there.

(One aside: `/usr/bin/nomad` wouldn't work because `/usr` is read-only, except for `/usr/local` which is a symlink to `/var/usrlocal`. So e.g. `/var/usrlocal/bin/nomad` would be more appropriate.)

**Closed by jlebon** 2021-01-21 19:02 UTC
Labels: kind/enhancement
