### ISSUE TITLE
Make FCOS available on the Azure Marketplace

### ISSUE THREAD

**Issue by jomeier** [coreos/fedora-coreos-tracker#435] opened 2020-03-26 10:48 UTC
Hi everybody,

now that the Azure DNS issue seems to be fixed:

https://github.com/coreos/fedora-coreos-tracker/issues/356

(thanks a lot for your effort!) 

how far away are we to bring the released image on the Azure marketplace?

OKD 4 is short before getting released and there is a strong dependency in it’s Azure version for having the FCOS image on the Azure marketplace.

If you need somebody who tests the setup  you can count on me.

Thanks a lot and greetings,

Josef

**Comment by dustymabe** [comment] 2020-03-26 13:14
Thanks for the offer Josef. We are trying but I don't have any dates or guidance on a timeline for you.

**Comment by jomeier** [comment] 2020-03-26 14:41
What are the showstoppers? We have good contacts to Azure if that helps.

**Comment by jomeier** [comment] 2020-03-26 14:56
Azure Shared Galleries could be an alternative instead of using the Azure Marketplace.

**Comment by bgilbert** [comment] 2020-03-27 00:58
It appears that Azure Shared Galleries cannot be used to make an image public.

Closing as a duplicate of #148.

**Closed by bgilbert** 2020-03-27 00:58 UTC
