### ISSUE TITLE
Image for DigitalOcean

### ISSUE THREAD

**Issue by tyranron** [coreos/fedora-coreos-tracker#395] opened 2020-02-18 08:52 UTC
Similar to #355 

I have recently played with Terraform, DigitalOcean and FCOS, without success, however. DigitalOcean doesn't provide prepared FCOS image at the moment, nor I could create [custom DO image](https://developers.digitalocean.com/documentation/v2/#create-a-custom-image) using any link from [`stable.json`](https://builds.coreos.fedoraproject.org/streams/stable.json). The problem is quite nasty: whille DO accepts `qcow2`/`raw` formats, it doesn't accept them packed into `.xz` archive, only `gzip`/`bzip2` 😕

Also, I didn't found any capabilities to launch DO droplet in "rescue mode" to install FCOS via `coreos-installer`.

It would be very nice to have at least DO-compatible images at [download page](https://getfedora.org/coreos/download/) to use them as custom ones.

Thank you!

**Comment by lucab** [comment] 2020-02-18 09:02
Cross-referencing: https://github.com/coreos/fedora-coreos-tracker/issues/151

**Comment by lucab** [comment] 2020-02-18 13:35
Last status update was at https://github.com/coreos/fedora-coreos-tracker/blob/52cb105c15aadd9b1cf70fc8b55fe91f49f74431/Design.md#digitalocean. I am not aware of any changes since then.

**Comment by bgilbert** [comment] 2020-02-18 23:59
Thanks for the report.  I've added https://github.com/coreos/fedora-coreos-tracker/issues/151#issuecomment-587963985 suggesting that we provide custom images to use with DHCP while waiting for proper DigitalOcean networking support to land in FCOS.  I suspect we'll continue shipping xz-compressed images though; the expectation is that users will uncompress them before uploading.

Closing this as a duplicate of #151.

**Closed by bgilbert** 2020-02-18 23:59 UTC
Labels: cloud*

**Comment by tyranron** [comment] 2020-02-19 08:33
@bgilbert thanks for the clarification.

>  I suspect we'll continue shipping xz-compressed images though; the expectation is that users will uncompress them before uploading.

This, unfortunately, doesn't automate well. [DO's `POST /v2/images`](https://developers.digitalocean.com/documentation/v2/#create-a-custom-image) supports only specifying files via URL, it doesn't allow in-place multipart uploading or something like that. And while the downloading and re-compressing is not a big deal for automation tools like Terraform, the uploading to some place to have that link __is__, actually.

I'm not against xz-compressing, but is it possible to provide alternatives, or, at least one `raw` uncompressed image?

**Comment by bgilbert** [comment] 2020-02-21 06:03
> This, unfortunately, doesn't automate well. DO's POST /v2/images supports only specifying files via URL, it doesn't allow in-place multipart uploading or something like that.

Ah, thanks for the clarification.  Yes, we could special-case compression for this artifact.  Noted in https://github.com/coreos/fedora-coreos-tracker/issues/151#issuecomment-589512233.
