### ISSUE TITLE
PXE boot fails with confusing "hash mismatch" error if the rootfs does not exist on the server

### ISSUE THREAD

**Issue by N3rdle** [coreos/fedora-coreos-tracker#1390] opened 2023-01-25 22:04 UTC
Hi all.

it appears that the pxe live initramfs for the 37.20230110.3.1 image that was just released over night has the wrong hash of the live rootfs embedded within it. This works perfectly for the prior stable release, and existing operational fedora coreos instances upgrade to this release perfectly but any new installations using pxe on this release fail.

![image](https://user-images.githubusercontent.com/4164438/214701822-b5b80060-82bb-4410-bd8e-20e648260bf6.jpg)

**Comment by bgilbert** [comment] 2023-01-25 22:13
I just PXE-booted this release locally and it works for me.  Can you confirm that your copy of the `rootfs` artifact has SHA-256 hash `0ae167d335a7a2a26bf93375dfdf06d02bb2912e211899a4b5f3a0df55c1fff0`?

**Comment by N3rdle** [comment] 2023-01-26 00:05
That’s exactly the hash of the file I have here.

**Comment by bgilbert** [comment] 2023-01-26 05:02
Digging a bit more, it looks like you're using the wrong initrd.  `1f2fd8771...` is the correct hash of the first two MiB of the 37.20230110.3.1 `rootfs`.  I'm not sure where your initrd could have come from, though.  I checked the last year's worth of `stable`, `testing`, and `next` releases for a first chunk matching `91b6b69...` and didn't find any.  Could you confirm the SHA-256 of your initrd?

**Comment by N3rdle** [comment] 2023-01-26 06:14
I’ll do that first thing in the morning.

The initrd came from the download page on the website (the links adjacent
to that for the rootfs) and I confirmed it’s hash and signature against
what was showed on the web site before ever reporting anything…

I’ll give you the hash ASAP in the morning, but it matched what the web
site showed at the time I did this…

Cheers

Peter

**Comment by N3rdle** [comment] 2023-01-26 06:15
Correction: I did a customization of that initrd for my environment. So I’m
sure that’s got something to do with this…

Sorry for the hassle.

Cheers

Peter

**Comment by bgilbert** [comment] 2023-01-26 06:20
If you used `coreos-installer pxe customize`, that shouldn't affect the embedded rootfs hashes.  So the thing to check is what initrd your custom one was based on.

**Comment by N3rdle** [comment] 2023-01-26 12:03
Roger. Makes total sense.

I’m very confident that at the time I grabbed the images, it totally
matched what was on the website as the latest for 3.1, but I’ll check here
in a bit.

Cheers

Peter

**Comment by N3rdle** [comment] 2023-01-26 14:03
Confirmed correct:

**Comment by dustymabe** [comment] 2023-01-26 14:28
Is there still a problem? @N3rdle is there a set of steps you can take (starting with downloading the initramfs/rootfs/kernel from the download page) to reproduce an issue?

**Comment by N3rdle** [comment] 2023-01-26 15:06
Well, there’s good news, and a small bit of bad news :)

First of all, *I’m an idiot*

Bad news: this was caused by a 404 on the web server handing out the rootfs
image (I forgot to just move it into the *correct* directory)

So, something just seems a bit anemic in that logic to assess the http
request status.

Thank god, this is minor in comparison.

SORRY! So many thanks for the support, all involved!

Cheers

Peter

**Comment by dustymabe** [comment] 2023-01-26 15:11
Glad we got it figured out @N3rdle. I'll close this out for now.

**Comment by jlebon** [comment] 2023-01-26 17:34
Let's reopen this to track improving the error message in this case.

**Comment by jlebon** [comment] 2023-01-26 17:40
Weird, not sure how we managed to "close" this twice in a row without a reopen in between.

**Closed** 2023-01-30 18:24 UTC
