### ISSUE TITLE
FCOS os-release `PRETTY_NAME` deviates from the format all other editions use

### ISSUE THREAD

**Issue by AdamWill** [coreos/fedora-coreos-tracker#616] opened 2020-09-02 23:01 UTC
The `PRETTY_NAME` field in `/etc/os-release` in Fedora CoreOS builds follows this format:

Fedora CoreOS $VERSION

e.g. "Fedora CoreOS 32.20200824.2.0". But the same field in all other Fedora editions follows a different format:

Fedora $VERSION ($EDITION [Prerelease])

e.g. "Fedora 33 (Workstation Edition)" or "Fedora 33 (Workstation Edition Prerelease)" if it's a pre-release.

Does FCOS need to be an outlier here, or can it adopt the same format as other editions?

**Comment by AdamWill** [comment] 2020-09-02 23:02
Note even other ostree-based editions follow the second format just with a more ostree-y $VERSION, e.g. a recent Fedora-IoT compose has this for `PRETTY_NAME`:

Fedora 34.20200902.0 (IoT Edition Prerelease)

**Comment by AdamWill** [comment] 2020-09-02 23:14
per https://github.com/coreos/fedora-coreos-tracker/issues/245 , this was done on purpose. Let's say I disagree with the rationale.

**Comment by lucab** [comment] 2020-09-14 12:34
I'm going ahead and closing+locking this as a duplicate of #245 to avoid forking the discussion thread there.

**Closed by lucab** 2020-09-14 12:34 UTC
