### ISSUE TITLE
Reboot/Upgrade nukes user specified systemd units - Regression

### ISSUE THREAD

**Issue by shivarammysore** [coreos/fedora-coreos-tracker#456] opened 2020-04-11 00:32 UTC
```rpm-ostree status``` will provide what version the current OS is running.  I am trying to find out exactly what time the update was applied.  Is there a way to raise a notification that OS was updated?

(I am trying to chase down an issue and want to rule out scenarios.  Hence the question)

**Comment by shivarammysore** [comment] 2020-04-11 01:01
One way that I found out when last upgrade was applied is by

```console
$ sudo journalctl -f -u zincati.service
-- Logs begin at Fri 2020-03-27 04:22:13 UTC. --
Apr 10 19:04:52 ip-10-0-9-162 zincati[693]: [INFO ] new release '31.20200323.3.2' selected, proceeding to stage it
Apr 10 19:05:37 ip-10-0-9-162 zincati[693]: [INFO ] staged deployment '31.20200323.3.2' available, proceeding to finalize it
Apr 10 19:05:39 ip-10-0-9-162 systemd[1]: Stopping Zincati Update Agent...
Apr 10 19:05:39 ip-10-0-9-162 systemd[1]: zincati.service: Succeeded.
Apr 10 19:05:39 ip-10-0-9-162 systemd[1]: Stopped Zincati Update Agent.
-- Reboot --
Apr 10 19:06:05 localhost systemd[1]: Started Zincati Update Agent.
Apr 10 19:06:05 localhost zincati[694]: [INFO ] starting update agent (zincati 0.0.9)
Apr 10 19:06:09 ip-10-0-9-162 zincati[694]: [INFO ] Cincinnati service: https://updates.coreos.stg.fedoraproject.org
Apr 10 19:06:09 ip-10-0-9-162 zincati[694]: [INFO ] agent running on node '09955f8c15c64998b728e5d1ea40949a', in update group 'default'
Apr 10 19:06:09 ip-10-0-9-162 zincati[694]: [INFO ] initialization complete, auto-updates logic enabled
^C
```

I had some `systemd` services which were enabled and running.

```console
[core@ip-10-0-0-10 ~]$  sudo systemd enable /home/core/myapp.service
[core@ip-10-0-0-10 ~]$  sudo systemd start /home/core/myapp.service
```

On upgrade, I had to reenable these services again manually for my stuff to work.  Is this a bug or feature?

**Comment by shivarammysore** [comment] 2020-04-11 01:53
BTW, this feature used to work in original CoreOS.

**Comment by lucab** [comment] 2020-04-11 08:05
@shivarammysore indeed, it looks like a strange behavior, though I'm not sure if it's related to the upgrade or just to reboots in general.
Can you please:
 * post your fcct (or Ignition) configuration
 * start from latest release, and see whether a simple reboot reproduces the issue
 * post the output of `systemctl status myapp.service`

**Comment by shivarammysore** [comment] 2020-04-11 18:11
After further tests, this is a problem after `reboot` too.  So, it is a much bigger problem for us now.  This is happening with this new release.  Earlier `reboot` worked correctly.
 We need to check for **upgrade** to a new release after `reboot` issue.
Ignition config: 
https://gist.github.com/shivarammysore/71d84dad336a1e7dfad8ed0c52b1bd22

Current `myapp` after I enabled and running it manually. 
```
$ systemctl status lb.service
● lb.service - Controller NginX Reverse Proxy
   Loaded: loaded (/var/home/core/lb.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2020-04-10 22:23:28 UTC; 19h ago
  Process: 35089 ExecStartPre=/usr/bin/docker kill lb-cntnr (code=exited, status=1/FAILURE)
  Process: 35095 ExecStartPre=/usr/bin/docker rm lb-cntnr (code=exited, status=0/SUCCESS)
 Main PID: 35101 (docker)
    Tasks: 7 (limit: 1050)
   Memory: 25.5M
   CGroup: /system.slice/lb.service
           └─35101 /usr/bin/docker run --name=lb-cntnr --network=host --volume=/home/core/lb-conf:/etc/nginx/conf nginx:1.17.9-alpine nginx -c /etc/nginx/conf/nginx.conf -g daemon>

Apr 11 14:30:33 ip-10-0-9-162 docker[35101]: 35.233.158.179 - - [11/Apr/2020:14:30:33 +0000] "GET /myadmin/scripts/setup.php HTTP/1.1" 301 169 "-" "ZmEu" "-"
```

**Comment by lucab** [comment] 2020-04-14 08:00
@shivarammysore your Ignition configuration does not contain (nor enable) any systemd service. That means that you (likely) performed some manual setup with custom content which is not part of this ticket. This makes it very hard on our side to automatically reproduce and investigate what you see.

I'd recommend to:
 * make a minimal scenario with a service unit under `/etc`
 * make a fcct / Ignition configuration which captures the whole set of customization above
 * deploy it from scratch on a machine with latest `stable` or `testing` release, and see if it works

**Comment by shivarammysore** [comment] 2020-04-14 15:13
@lucab I understand that reproducing can be hard.  This was a feature that used to work as I described from the CoreOS days to the last release.  It is not after this recent upgrade.  My simple question is why the regression?

**Comment by lucab** [comment] 2020-04-15 14:00
@shivarammysore it could be a bunch of things, from a wrong dependency specification on the unit itself, to some permission/policy preventing this to load on boot, to some corner-case behavior in handling of units in `/home`, to a bug in some software component.

Unfortunately this fails on a set of customization which is the result of specific manual actions. Thus, assuming it is not a human mistake somewhere, you'll have to track down what's going on your machine, and then let us know your findings. Or bring those to an Ignition config, which also helps zeroing out the chance of a human mistake / wrong config.

**Comment by shivarammysore** [comment] 2020-04-27 15:42
@lucab @dustymabe - My machines are in a very different state at this time and I have not found time to exactly provide a scenario so that you can replicate this.  If I can update the machine config via ignition file, then I will certainly have a workaround and is an acceptable solution for me.

**Comment by dustymabe** [comment] 2020-05-19 20:46
hey @shivarammysore - can you provide a reproducer for this? If not I'll close it out and you can re-open if you ever hit it again.

**Comment by shivarammysore** [comment] 2020-05-20 04:10
You can close it for now.  My infrastructure is drastically different.

**Closed** 2022-02-22 05:10 UTC
Labels: component/systemd, needs/more-information
