### ISSUE TITLE
Fails to ssh into instance on OpenStack

### ISSUE THREAD

**Issue by stamak** [coreos/fedora-coreos-tracker#508] opened 2020-05-29 13:18 UTC
Started with command
`nova boot --flavor flavor --image Fedora-Coros-syndeo  --key-name my-ssh-key --nic net-name=d6c895b794894a61a430978fe8085dd3-network  my-fedora-coreos-ssh-keys`

Trying to ssh
`[core@node1 ~]$ ssh 10.111.111.11 -l core
core@10.111.111.11: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).`

`rpm-ostree status
  ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 31.20200505.3.0 (2020-05-19T13:39:46Z)
                    Commit: 01f074cc6cd88d8d2b43f821da692f2367c101eb4377802cb35092bde0ef02f7
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4`

Seems Fedora CoreOS does not get ssh keys form configdrive/metadata ?

**Comment by lucab** [comment] 2020-05-29 13:45
Duplicate of https://github.com/coreos/fedora-coreos-tracker/issues/422.

**Closed by lucab** 2020-05-29 13:45 UTC
