### ISSUE TITLE
Installer kept rebooting while Installing CoreOS on Bare Metal

### ISSUE THREAD

**Issue by imranrazakhan** [coreos/fedora-coreos-tracker#350] opened 2020-01-22 13:44 UTC
I did following steps to install CoreOS

- Download an ISO image "fedora-coreos-31.20200113.3.1-live.x86_64.iso"

- Burn the ISO to disk and boot it on the target system. 

I was expecting bash command prompt. but it kept rebooting from below screen

![image](https://user-images.githubusercontent.com/8535886/72899060-8d2f6800-3d25-11ea-8382-71b2d2902d9e.png)

**Comment by lucab** [comment] 2020-01-22 15:10
Thanks for the report. This is unfortunately a bit hard to debug as is.
I can confirm the live ISO image you downloaded works in general, so it could be something specific to your setup.

Is this a physical server or virtual machine? Does it have at least 2 GiB of RAM in order to load the whole OS in memory? Does the system have a proper with DHCP available?

**Comment by imranrazakhan** [comment] 2020-01-22 16:06
Yes i can understand its really hard to debug. one observation is my USB was in PC and it rebooted around 5 to 6 times and after that it showed me bash (I thought it happen accidental so i tried again and same behavior again it restarted 6 times and 7 time it showed bash)

>> Is this a physical server or virtual machine?
Physical Server

>>Does it have at least 2 GiB of RAM in order to load the whole OS in memory?
RAM = 32GB
SDD = 500GB
Currently HardDisk was partitioned for CentOS but i dont think it would matter for booting

>>Does the system have a proper with DHCP available?
Yes its connected to network without internet but will get DHCP IP from router.

Does that matter if this PC already has DHCP IP ?

**Comment by jlebon** [comment] 2020-01-22 16:40
> it rebooted around 5 to 6 times and after that it showed me bash

Hmm, sounds like something is racing and somehow causing a reboot?

Does it immediately reboot, or do you have time to read what's on the screen? If so, what do you see? Kernel panic? systemd errors? Try again with `rd.break` maybe to see if you can at least consistently get to the emergency shell. This could tell us whether the issue is more likely to be during the initrd phase or in the real root.

**Comment by imranrazakhan** [comment] 2020-01-22 16:51
>> Does it immediately reboot, or do you have time to read what's on the screen?
it reboot immediately and no kernel panic or other errors. I recorded video of reboot and in-fact above screenshot was last frame of that video before reboot.

I will try with rd.break and share feedback.

To try with rd.break at Fedora OS Screen i will press TAB and at the end just type rd.break (please correct me if i am wrong) ?

**Comment by imranrazakhan** [comment] 2020-01-22 17:32
@jlebon I did following steps

- I booted from USB and it again rebooted
- On second time i entered rd.break and it landed to emergency shell
- I exit from this shell and it reached to bash without any reboot
- on bash saw following audit logs

![image](https://user-images.githubusercontent.com/8535886/72918194-87497f00-3d45-11ea-910f-a8d9ebb23b9f.png)

**Comment by jlebon** [comment] 2020-01-22 18:59
You can mostly ignore the audit log messages. It's just very chatty.

Another thing you can try is booting with systemd debugging on to see if you can catch anything:

```
systemd.log_level=debug systemd.log_target=console systemd.journald.forward_to_console=1
```

> Tomorrow i will try on second PC and will share details accordingly

:+1:

**Comment by imranrazakhan** [comment] 2020-01-24 20:09
@jlebon i tested on other MachineB with same model and specs but could not reproduce reboot issue, But on MachineA its coming every time, i Installed CentOS on MachineA and it was successful. So will try with more debug on MachineA.

**Comment by imranrazakhan** [comment] 2020-01-30 15:36
@jlebon after starting ISO with debug parameters it reached at this page

![image](https://user-images.githubusercontent.com/8535886/73463904-54733c80-437e-11ea-87bb-6a15b02f9361.png)

and now its repeating and showing following screen

![image](https://user-images.githubusercontent.com/8535886/73463979-753b9200-437e-11ea-8eb3-98a4084aaa7b.png)

You can see `systemd-journal.service: Got notification message` is repeating in both screen

**Comment by jlebon** [comment] 2020-01-31 15:26
Hmm I'm not sure. There's nothing super obvious from those screenshots.

> i tested on other MachineB with same model and specs but could not reproduce reboot issue, But on MachineA its coming every time

Hmm, the *exact* same hardware and configuration? This would suggest a hardware issue if so.

One thing also worth trying; if you can get to a succesful boot after reboots, you can try checking the logs of previous boots with e.g. `journalctl -b -1` and look for a smoking gun. You can also check `last -x` to figure out if it was a graceful shutdown (i.e. some service initiated it) or not.

**Comment by bgilbert** [comment] 2022-02-22 05:12
This is a couple years old, and debugging was inconclusive.  A lot has changed since this bug was filed, so it's likely no longer valid.  I'll go ahead and close it out.

**Closed by bgilbert** 2022-02-22 05:12 UTC
Labels: needs/more-information, platform/metal, format/live-iso
