### ISSUE TITLE
audit messages are flooding the console

### ISSUE THREAD

**Issue by lucab** [coreos/fedora-coreos-tracker#220] opened 2019-07-18 12:50 UTC
On a freshly booted instance, the console is quickly filled with audit messages from the kernel. This makes spotting the `<INTERFACE>:<IPs>` harder, and any interactive console usage very messy.

This seems to be caused by our console level being very low (7 is debug):
```
$ sysctl kernel.printk
kernel.printk = 7       4       1       7
```

I am not sure where this is coming from, though. For the moment, it can be work-arounded with the following snippet in `/etc/sysctl.d/10-kernel-printk.conf`:

```
kernel.printk=4
```

### OS info
```
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora:fedora/x86_64/coreos/testing
                   Version: 30.20190716.0 (2019-07-16T15:00:38Z)
                    Commit: b25e7016d621c9d308747ccc4a886224488aa506290c0f8246f3c15216ba2a5c
              GPGSignature: (unsigned)
```

**Comment by dustymabe** [comment] 2019-08-06 20:37
are you saying we should use a different value for `CONFIG_CONSOLE_LOGLEVEL_DEFAULT` in [the fedora kernel configs](https://src.fedoraproject.org/rpms/kernel/blob/master/f/configs/fedora/generic/CONFIG_CONSOLE_LOGLEVEL_DEFAULT) ?

**Comment by dustymabe** [comment] 2019-08-06 20:52
FTR `7       4       1       7` seems to be the default on debian 10 (buster) as well

**Comment by arithx** [comment] 2019-08-07 16:04
I'd bring up that notably having some debugging messages printed on the console is useful even in production use cases. Specifically when interacting with clouds one of the primary ways of fetching information about a node that you cannot SSH into is using the built-in cloud APIs to fetch the console. This is especially important in the case of Ignition failures.

I do agree that some of the audit spam is not optimal but that might be something we want to look into directly rather than lowering the entire console log level.

**Comment by dustymabe** [comment] 2019-08-07 16:07
> I do agree that some of the audit spam is not optimal but that might be something we want to look into directly rather than lowering the entire console log level.

:+1: 

benjamin also mentioned that `7 4 1 7` was the default on CL too

**Comment by lucab** [comment] 2019-08-07 16:11
Sorry for the confusion, I am not suggesting to lower the defaults. At least not without further investigation first. This was just to track that I had some friction in getting the IP from the serial console due to audit spam, and that tweaking the sysctl helped.

**Comment by dustymabe** [comment] 2020-04-02 14:03
ok I'm working on setting up some sort of interactive TUI experience for our live ISO installer and having audit messages periodically print to the screen is not a good user experience.  From what I can tell there are a few options to fix this issue:

- change kernel logging level defaults (as mentioned earlier in this ticket)
- set `audit=0` on the kernel command line
- add `auditd` to the host

I'm not sure how bad it would be to disable auditing (`audit=0`). If there is a silver lining to adding `auditd` to the host it would be that we get back an easy way to find SELinux denials (via `ausearch -m avc`). Currently the `audit` rpm has one dependency that would get brought in but it's not one we need and I [opened a PR to remove it altogether](https://src.fedoraproject.org/rpms/audit/pull-request/5).

**Comment by lucab** [comment] 2020-04-02 17:21
Followup from IRC: we generally like getting audit events. We don't hardcode any `audit=` karg on the kernel command-line. Journald correctly receives the audit event and they are available in the journal (with `_TRANSPORT=audit`). It looks like journald itself [enables](https://github.com/systemd/systemd/blob/v245/src/journal/journald-audit.c#L471) auditing. As we are not running anything else (i.e. no `auditd`), there may be some missing logic in journald that results in the kernel kprint-ing event to console. We are going to check this behavior with systemd folks.

**Comment by lucab** [comment] 2020-04-03 17:14
Tracked at https://github.com/systemd/systemd/issues/15324.

**Comment by lucab** [comment] 2020-04-07 13:44
According to the above systemd ticket, we pinpointed this to a limitation / missing feature in the kernel audit subsystem.
The recommendation is that right now the sanest path is to also ship auditd, possibly with the caveat that we may want to drop it when the kernel gets fixed in the future.

**Comment by dustymabe** [comment] 2020-04-07 14:12
👍 - there is a lot of context in that ticket that provides useful historical information. Thanks for opening that issue @lucab and following up here.

I'd propose we add `auditd` with a comment about the kernel issue (a link where we could track the kernel issue would be real nice). I shamelessly don't mind having `auditd` myself because of the `ausearch -m avc` functionality to search for and help diagnose SELinux denials.

**Comment by bgilbert** [comment] 2020-04-07 18:04
It appears there might be some movement in https://github.com/linux-audit/audit-kernel/issues/102.

Meanwhile, if we ship auditd as a short-term workaround, we'll inevitably get objections once we try to remove it again.  Would it make sense to write a small daemon that registers with the kernel using auditd's interface and then drops all messages?

**Comment by bgilbert** [comment] 2020-04-08 22:12
I did some digging.  Container Linux ships `auditctl` but not `auditd`, along with an [audit-rules.service](https://github.com/coreos/coreos-overlay/blob/master/sys-process/audit/files/audit-rules.service) which loads the audit rules on boot.  The default audit rules disable most auditing, but users can change those rules and the resulting messages will go to the journal.

On Fedora CoreOS, though, we're not shipping a way to load audit rules into the kernel, so we don't have a coherent audit solution right now.  We should at least ship `auditctl`.  It's in the same package as `auditd`, so maybe we should ship that too and not worry about it.  Alternatively, we could filter out `auditd` and add something like `audit-rules.service`.  In the latter case, if we enable some auditing by default, we might also want to ship a boilerplate `auditd` replacement to avoid the logging issue until the kernel is fixed.  It [shouldn't be too hard to write one](https://godoc.org/github.com/mozilla/libaudit-go).

**Comment by lucab** [comment] 2020-04-09 08:04
@bgilbert thanks for the trip in CL land. We have indeed a larger story to untangle wrt loading audit rules. I previously opened https://github.com/linux-audit/audit-userspace/issues/111 in order to get support for fragments. I'm both wary of just sticking to current `auditd` status and writing a scratch-new replacement.

(Drifting away from this ticket, I think it'd makes sense to split auditd / augenrules / auditctl binary packages anyway. If nobody opposes, I'm going to ask for that in bugzilla)

**Comment by dustymabe** [comment] 2020-04-09 14:06
my $.02: let's just ship auditd and spend our time solving other problems. I don't feel super strongly about it though.

**Comment by jamescassell** [comment] 2020-04-09 14:30
I feel we should ship auditd, as many security compliance regimes require such functionality, so it'd end up layered otherwise in many cases.

**Comment by jlebon** [comment] 2020-04-09 14:42
I'd be very wary of pulling in `initscripts`. It's a bunch of legacy stuff which has caused lots of issues for us in the past.

**Comment by dustymabe** [comment] 2020-04-09 14:50
> > I'd be very wary of pulling in `initscripts`. It's a bunch of legacy stuff which has caused lots of issues for us in the past.
> 
> I agree. If we ship auditd I think we should rip out initscripts.

https://github.com/coreos/fedora-coreos-config/pull/340 should help us make sure it doesn't get pulled in.

**Comment by dustymabe** [comment] 2020-04-15 04:02
This need to fix this is increased right now because we are trying to support a workflow where a user can interactively do an install using the Live ISO and use TUI interfaces for configuring networking.  The increased user experience provided by a TUI is completely lost if we have audit messages scrolling on the console every 10 seconds or so.

I have opened two change requests that are two options we have for fixing this problem immediately. They are meant to spark discussion and hopefully get us to a point where this problem is fixed for the user trying to run a TUI and not have audit messages scrolling across their TUI canvas.

- [live: disable audit on Live ISO](https://github.com/coreos/fedora-coreos-config/pull/347)
- [manifest: include audit rpm](https://github.com/coreos/fedora-coreos-config/pull/348)

Maybe we can discuss these options (or any other viable short term option) in the meeting today to see if we can make progress.

**Comment by dustymabe** [comment] 2020-04-15 16:35
I added a 3rd option to the bulleted list in https://github.com/coreos/fedora-coreos-tracker/issues/220#issuecomment-613803086

**Comment by dustymabe** [comment] 2020-04-15 19:39
We talked about this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/47WKLNVAL5UJTOVDR4YR2RVB6AJUJKY2/):

```
13:01:58  dustymabe | #agreed We have some outstanding issues that we'd like to try to push in
                    | audit upstream before we include that package in FCOS. For now we will
                    | quiet the kernel log level printed to the console of the machine and
                    | continue to push upstream for changes to make things more ideal
```

This is the [overlay: lower kernel console logging level on Live ISO](https://github.com/coreos/fedora-coreos-config/pull/352) option from https://github.com/coreos/fedora-coreos-tracker/issues/220#issuecomment-613803086.

I also agreed to open a ticket to discuss audit upstream features and packaging changes we'd like to see. It is here: https://github.com/coreos/fedora-coreos-tracker/issues/461

**Comment by egeturgay** [comment] 2020-04-21 15:05
> I did some digging. Container Linux ships `auditctl` but not `auditd`, along with an [audit-rules.service](https://github.com/coreos/coreos-overlay/blob/master/sys-process/audit/files/audit-rules.service) which loads the audit rules on boot. The default audit rules disable most auditing, but users can change those rules and the resulting messages will go to the journal.

> 
> On Fedora CoreOS, though, we're not shipping a way to load audit rules into the kernel, so we don't have a coherent audit solution right now. We should at least ship `auditctl`. It's in the same package as `auditd`, so maybe we should ship that too and not worry about it. Alternatively, we could filter out `auditd` and add something like `audit-rules.service`. In the latter case, if we enable some auditing by default, we might also want to ship a boilerplate `auditd` replacement to avoid the logging issue until the kernel is fixed. It [shouldn't be too hard to write one](https://godoc.org/github.com/mozilla/libaudit-go).

+1 for auditctl, we currently use (on CoreOS) for enabling auditd's file integrity checking feature by adding rules where it's a requirement from a PCI compliance perspective.

**Comment by egeturgay** [comment] 2020-04-22 12:27
added our use case of audit messages in journald in https://github.com/coreos/fedora-coreos-tracker/issues/461 but thought I should elaborate the fact that we use the logging in journald for compliance purposes by using log delivery agents parsing journald[audit] messages. 

As there is no auditd.log on Container Linux, that is the only way for us to be able to parse audit messages. Bringing auditd would solve this as suggested but we haven't found an disadvantage of getting the logs from journald vs getting it from auditd.log in terms of compliance requirements.

In addition to the above, FCOS currently does not ship auditctl and augenrules (unlike Container Linux) which prevents us using file integrity monitoring rules on FCOS.

We would appreciate any estimation or timelines in concluding the above to have enough time to look into alternatives if this is unlikely to land on to FCOS before the Container Linux EOL dates.

**Comment by dustymabe** [comment] 2020-06-16 21:39
For those hitting this that don't care about a lowered kernel log level you can workaround with:

```
$ cat fcct_silence_audit.yaml
variant: fcos
version: 1.1.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAA...
storage:
  files:
    - path: /etc/sysctl.d/20-silence-audit.conf
      contents:
        inline: |
          # Raise console message logging level from DEBUG (7) to WARNING (4)
          # so that audit messages don't get interspersed on the console that
          # may frustrate a user trying to interactively log in.
          kernel.printk=4
```

**Comment by cig0** [comment] 2022-10-29 17:23
Hi everybody,

I can confirm this is still happening with the latest image of IoT, `Fedora-IoT-ostree-x86_64-37-20220910.0.iso`

**Comment by dustymabe** [comment] 2022-10-29 17:38
Hey @cig0 - this is the Fedora CoreOS issue tracker. It's unrelated to Fedora IoT. You'll want to report any issues to their issue tracker.

**Comment by dustymabe** [comment] 2023-09-12 16:55
So this issue should now be solved in multiple ways. First, we now [lower the printk level after boot](https://github.com/coreos/fedora-coreos-tracker/issues/1244). Second, in F39+ we're going to [include auditd](https://github.com/coreos/fedora-coreos-tracker/issues/1362#issuecomment-1714252656).

I'll close this out now.

**Closed by dustymabe** 2023-09-12 16:55 UTC
Labels: jira, kind/friction, needs/investigation
