### ISSUE TITLE
Fedora CoreOS website doesn't have cloud launch buttons for AWS,Azure and only exist for GCP 

### ISSUE THREAD

**Issue by onuralpszr** [coreos/fedora-coreos-tracker#1740] opened 2024-05-27 23:31 UTC
Hello I know notice that azure and aws images being made for coreOS but there is no cloud launchable button exist could you please add those buttons so we can launch easier

Thank you.

Ref: https://fedoraproject.org/coreos/download?stream=stable

**Comment by jlebon** [comment] 2024-05-29 13:41
For AWS, there's a button to list the available regions and then launch buttons for each one.

There is no launch option for Azure because we don't currently upload there. This is tracked at https://github.com/coreos/fedora-coreos-tracker/issues/148. Let's close this one as a dupe of that one.

**Closed by jlebon** 2024-05-29 13:41 UTC

**Comment by onuralpszr** [comment] 2024-05-29 23:22
> For AWS, there's a button to list the available regions and then launch buttons for each one.
> 
> There is no launch option for Azure because we don't currently upload there. This is tracked at #148. Let's close this one as a dupe of that one.

Thank you
