### ISSUE TITLE
initrd: nm-initrd.service fails to spawn depending on console setup

### ISSUE THREAD

**Issue by kai-uwe-rommel** [coreos/fedora-coreos-tracker#943] opened 2021-08-29 14:50 UTC
**Describe the bug**
I regularly deploy OKD clusters with FCOS on vSphere.
The deployment process worked fine up until FCOS 34.2021-06-26 and started failing with 2021-07-11 and still fails with 2021-07-25 and 2021-0808.
The OKD cluster VMs start with plain FCOS OVA and get an igition file passed via guestinfo.ignition from vSphere.
Starting with FCOS 34.2021-07-11, the VMs simply fail to start their network.

**Reproduction steps**
1. create a VM from the FCOS OVA
2. configure an OKD ignition file via guestinfo.ignition
3. power on the VM

**Expected behavior**
As usual, the VM should initialize their network (with DHCP) and process the ignition file which includes merging an additional remote ignition file.

**Actual behavior**
The VM does not start its network, is not pingable and cannot resolve the remote http server (and can not connect to it) from which the initial ignition file (passed from vSphere via guestinfo.ignition) tries to merge a remote ignition file.

**System details**
All on a vSphere 7.0u2 cluster.
FCOS versions see above.

**Ignition config**
File attached here as text file.

**Additional information**
I tried to gather more details about why the boot process fails to start the networking by connecting a virtual serial console to the VM, in order to view serial console output and record it.
Unfortunately, when a serial console is connected to the VM, then the networking starts successfully.
So it looks like it is a timing issue and the serial console slows it down enough to let it succeed.

[initial-ignition.txt](https://github.com/coreos/fedora-coreos-tracker/files/7072713/initial-ignition.txt)

**Comment by kai-uwe-rommel** [comment] 2021-08-29 15:01
What I can see in the console as it passes by quickly (as described, I cannot reproduce with a serial console and can thus not record it):
![grafik](https://user-images.githubusercontent.com/26381804/131255092-b7cac870-c10e-4062-bc65-1b9f87b67779.png)

**Comment by dustymabe** [comment] 2021-08-30 13:32
This may be fallout from https://github.com/coreos/fedora-coreos-tracker/issues/842 (mainly because it was first implemented in `34.20210711.3.0`). If you remove OKD from the equation can you still reproduce with just a simple remote Ignition config?

**Comment by kai-uwe-rommel** [comment] 2021-08-30 13:48
Without OKD, e.g. some basic standalone VM with an otherwise similar (but purely local, e.g. completely within guestinfo.ignition) ignition file (just without the merged in remote/secondary ignition file) comes up fine. I would need to construct a case where I configure a standalone VM but with a merged in add'l remote ignition file ... did not have that case yet.

**Comment by dustymabe** [comment] 2021-08-30 13:56
> Without OKD, e.g. some basic standalone VM with an otherwise similar (but purely local, e.g. completely within guestinfo.ignition) ignition file (just without the merged in remote/secondary ignition file) comes up fine.

Yep. We have some logic in there that won't bring up networking at all if there are no remote references.



> I would need to construct a case where I configure a standalone VM but with a merged in add'l remote ignition file ... did not have that case yet.

+1 - it may be easy enough just to provide `ignition.config.url=http://...` on the kernel command line. Or it's possible it's triggered different, but we could start there.

**Comment by lucab** [comment] 2021-08-30 14:04
@kai-uwe-rommel is this node set up via DHCP (specifically, for the initrd and Ignition fetch), or does it have some custom networking configuration via guestinfo or kargs?

**Comment by kai-uwe-rommel** [comment] 2021-08-30 14:08
This is via DHCP.

**Comment by kai-uwe-rommel** [comment] 2021-08-30 14:09
As I tried to express above: this seems a timing issue. When I attach a serial console to debug, the problem vanishes away. Does this ring some bell for someone of you?

**Comment by zfiel** [comment] 2021-08-30 15:14
> As I tried to express above: this seems a timing issue. When I attach a serial console to debug, the problem vanishes away. Does this ring some bell for someone of you?

Thank you @kai-uwe-rommel, it solved my [problems](https://github.com/openshift/okd/discussions/830#discussion-3536456).

**Comment by kai-uwe-rommel** [comment] 2021-08-30 15:52
> 
> 
> > As I tried to express above: this seems a timing issue. When I attach a serial console to debug, the problem vanishes away. Does this ring some bell for someone of you?
> 
> Thank you @kai-uwe-rommel, it "solved" my [problems](https://github.com/openshift/okd/discussions/830#discussion-3536456).

???

_I_ am having a problem. In what way could this have solve your problem??

**Comment by dustymabe** [comment] 2021-08-30 17:48
> _I_ am having a problem. In what way could this have solved your problem??

well - in the very least it using the serial console (as you suggested) would allow someone to workaround the issue and get unblocked. So maybe that's what they meant.

**Comment by zfiel** [comment] 2021-08-30 19:36
Yes sorry it dit not solved the root issue, but at least I am able to get my cluster working again, by attaching a serial console (as a workaround).

**Comment by kai-uwe-rommel** [comment] 2021-08-31 10:05
Back to the topic - what next?
Anything I can do to help create debug logs or whatever?
The problem is not going away on its own ... :-(

**Comment by dustymabe** [comment] 2021-08-31 13:35
> Anything I can do to help create debug logs or whatever?

Yep. It would still be nice to get a simple reproducer *without* OKD.

**Comment by lucab** [comment] 2021-08-31 14:07
I did manage to reproduce this outside of OKD on latest `stable` (34.20210808.3.0), just with an Ignition config with a reference to a remote resource.
`nm-initrd.service` is conditional on the initrd `neednet`, and a remote reference in Ignition will plug into it.

I'm having some hard time catching the real error.
Adding a serial device makes this go away, but the same effect also happens if I drop all `console=` kargs in order to get an emergency shell.
As such, I suspect this is not merely a timing race which can get affected by attaching a serial device, but a plain bug related to the node console setup.

**Comment by lucab** [comment] 2021-08-31 14:15
After a few tries, I did manage to capture the failure:
![nm-initrd](https://user-images.githubusercontent.com/98086/131517851-af12a776-e4f5-4155-b9da-098905ef0814.png)

I think this is due to `nm-initrd.service` unit having a `StandardOutput=tty` in its service definition, see https://github.com/dracutdevs/dracut/blob/055/modules.d/35network-manager/nm-initrd.service#L19.

I believe this isn't vmware-specific, but may affect any setup with a mismatched console configuration.

**Comment by kai-uwe-rommel** [comment] 2021-08-31 14:27
Ok. This sounds like this can/will be fixed in near future?

**Comment by lucab** [comment] 2021-08-31 14:42
Yes, I think this could be simply fixed by dropping the `StandardOutput=` config, although I'm not sure why it's there in the first place.
@bengal do you maybe remember why you set it up this way?

Sidenote: I won't be able to push this forward anytime soon, as I'm about to go offline for a few days.

**Comment by bengal** [comment] 2021-09-06 08:36
`StandardOutput=tty` was added so that NM output is visible in the console (which is useful especially with `rd.debug`). I'll try to reproduce and find a different solution.

**Comment by lucab** [comment] 2021-09-06 09:07
@bengal ack. In that case I think you can try to see whether `StandardOutput=journal+console` is ok too.

**Comment by cgwalters** [comment] 2021-09-07 15:28
> Perhaps we should add a configuration option (or command line switch) so that NM can write only to stdout (and then the service will use StandardOutput=journal+console)

Yes, that makes the most sense to me, then systemd handles everything (and presumably does so in a race-free way).

**Comment by bengal** [comment] 2021-09-10 08:29
NM discussion here: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/merge_requests/977

**Comment by kai-uwe-rommel** [comment] 2021-09-12 10:33
How will I know when and with which release of FCOS the fix will be delivered?

**Comment by bengal** [comment] 2021-09-14 08:17
> Adding a serial device makes this go away, but the same effect also happens if I drop all `console=` kargs in order to get an emergency shell.

What did you have configured as `console=`?

Is the problem that there is a console= karg, and the hardware is missing?

**Comment by HaehnleinMar** [comment] 2021-09-14 08:58
On vSphere it worked for me when I add a serial port to the VM.

**Comment by lucab** [comment] 2021-09-14 09:12
Noting this down for reference, answering for the details of the OVA on VMware where I reproduced it.

> What did you have configured as console=?

The kernel command-line contains `console=tty0 console=ttyS0,115200n8` (in this specific order). At the time of this writing, this is the default for the OVA. It can be configured later on, but the failure observed here happens in the initrd at the beginning of the first boot (i.e. before machine-specific configuration tweaks can be fetched/applied).

> Is the problem that there is a console= karg, and the hardware is missing?

I believe so, given that:
 * the reported boot failure happens with `console=tty0 console=ttyS0,115200n8` and no serial peripheral attached
 * from other reports, attaching a serial peripheral (i.e. `ttyS0`) to the VM results in a successful boot
 * from my own experimentation, dropping the `console=ttyS0,115200n8` bits results in a successful boot (i.e. leaving only `console=tty0`

**Comment by dustymabe** [comment] 2021-09-14 14:16
> How will I know when and with which release of FCOS the fix will be delivered?

We'll report here updates and also when the issue is fixed and in what release.

**Comment by dustymabe** [comment] 2021-09-21 15:24
hey @lucab @bengal - where did we land on this? Can we make progress?

**Comment by sandrobonazzola** [comment] 2021-10-01 14:47
Seems like I hit this issue as well, thanks @kai-uwe-rommel for pointing here.

**Comment by kai-uwe-rommel** [comment] 2021-10-21 11:57
Any news about when a release to be expected?

**Comment by dustymabe** [comment] 2021-11-01 15:48
Fixed by:

- https://github.com/coreos/fedora-coreos-config/pull/1310
- https://github.com/coreos/fedora-coreos-config/pull/1309

**Comment by dustymabe** [comment] 2021-11-03 16:12
The fix for this went into next stream release `35.20211029.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment] 2021-11-03 16:13
The fix for this went into testing stream release `34.20211031.2.0`. Please try out the new release and report issues.

**Closed** 2021-11-03 16:13 UTC
Labels: kind/bug, jira, component/NetworkManager, status/pending-stable-release, area/initramfs

**Comment by kai-uwe-rommel** [comment] 2021-11-05 20:27
I just did a cluster installation with 34.20211031.2.0 on vSphere UPI and the fix seems to work properly. All nodes started fine.

**Comment by dustymabe** [comment] 2021-11-11 15:39
The fix for this went into stable stream release `34.20211031.3.0`.
