### ISSUE TITLE
Latest link to bare metal & virtualized images

### ISSUE THREAD

**Issue by sergeiwaigant** [coreos/fedora-coreos-tracker#706] opened 2020-12-27 15:07 UTC
Hi all,

I am spinning up Fedora CoreOS on my ESXi system via PXE and at the moment I need to run the coreos-installer to get the PXE files, update the pxelinux config and distribute them accordingly.

For Fedora and CentOS Stream I am using the provided mirrors directly like shown below to get the necessary PXE boot files.

On the download website the links to kernel, initramfs and rootfs are pointing to the latest version, but explicitly.
Is there a link directly to the "latest" version of that files?

Regards
Sergei

- https://getfedora.org/en/coreos/download?tab=metal_virtualized&stream=stable

```
label f33-kickstart
  menu label ^Install Fedora 33 ( Kickstart )
  kernel https://download.fedoraproject.org/pub/fedora/linux/releases/33/Server/x86_64/os/images/pxeboot/vmlinuz
  append ip=dhcp noipv6 ipv6.disable=1 initrd=https://download.fedoraproject.org/pub/fedora/linux/releases/33/Server/x86_64/os/images/pxeboot/initrd.img inst.stage2=https://download.fedoraproject.org/pub/fedora/linux/releases/33/Server/x86_64/os/ inst.ks=http://truenas/pxeboot/f33/kickstart.cfg

label centos8-kickstart
  menu label ^Install CentOS Stream 8 ( Kickstart )
  kernel http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/images/pxeboot/vmlinuz
  append ip=dhcp noipv6 ipv6.disable=1 initrd=http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/images/pxeboot/initrd.img inst.stage2=http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/ ks=http://truenas/pxeboot/centos8/kickstart.cfg

label fcos-stable
  menu label ^Start Fedora Core OS Stable
  kernel fcos/fedora-coreos-33.20201201.3.0-live-kernel-x86_64
  append ip=dhcp noipv6 ipv6.disable=1 initrd=http://truenas/pxeboot/fcos/fedora-coreos-33.20201201.3.0-live-initramfs.x86_64.img,http://truenas/pxeboot/fcos/fedora-coreos-33.20201201.3.0-live-rootfs.x86_64.img coreos.inst.install_dev=/dev/sda coreos.inst.ignition_url=http://truenas/pxeboot/fcos/fcos.ign
```

**Comment by dustymabe** [comment] 2020-12-27 15:52
Hi @sergeiwaigant, thanks for using Fedora CoreOS!

This request is a duplicate of the one over in #625. It's something we'd like to do but isn't a high priority so it might take some time. See the statement at https://github.com/coreos/fedora-coreos-tracker/issues/625#issuecomment-697943279 and the following comments.

**Closed by dustymabe** 2020-12-27 15:52 UTC
