### ISSUE TITLE
Release Notes for New Images

### ISSUE THREAD

**Issue by imranrazakhan** [coreos/fedora-coreos-tracker#389] opened 2020-02-13 13:11 UTC
I just saw new Live ISO is available to download, where we can find release notes, whats fixed in it or what feature is introduced?

**Comment by lucab** [comment] 2020-02-13 13:22
Please do note that we have a discussion forum for questions at https://discussion.fedoraproject.org/c/server/coreos.

Specifically on release notes, we still don't have a proper flow in place but we are discussing approaches at https://github.com/coreos/fedora-coreos-tracker/issues/194. Closing as a duplicate of that.

**Closed by lucab** 2020-02-13 13:22 UTC
Labels: area/usability, kind/question
