### ISSUE TITLE
Bump dracut as mdio is not included in initramfs

### ISSUE THREAD

**Issue by wernerb** [coreos/fedora-coreos-tracker#781] opened 2021-04-02 08:52 UTC
**Describe the bug**
An upstream dracut bug has been solved in dracut-052: https://github.com/dracutdevs/dracut/commit/3c8ca29 
We have dracut 051 on the next-develop/next branch. I suggest bumping this to dracut-053 which is fedora 34 stable so that mdio gets properly loaded. This has been a bug since the change to kernel 5.10

See redhat issue: https://bugzilla.redhat.com/show_bug.cgi?id=1943983

**Expected behavior**
The mdio modules are included

**Actual behavior**
The mdio are not included due to a kernel change splitting `phy`.

**System details**
On all platforms

**Comment by lucab** [comment] 2021-04-06 13:19
Thanks for the report, this should happen automatically on the next release on that stream. You can track its schedule and updates at https://github.com/coreos/fedora-coreos-streams/issues/288.

**Comment by lucab** [comment] 2021-04-15 09:27
Unfortunately we are currently keeping `dracut` pinned to an older version due to other regressions, see https://github.com/coreos/fedora-coreos-tracker/issues/782. Version bump will happen at a later point once those regressions are fixed.

**Comment by dustymabe** [comment] 2021-04-15 13:30
Luckily we've got a proposed fix (https://github.com/coreos/fedora-coreos-config/pull/958) out for #782. Just waiting to get a little more feedback on the upstream PR to dracut itself (https://github.com/dracutdevs/dracut/pull/1347) before we merge that.

**Comment by dustymabe** [comment] 2021-04-16 16:47
Should be fixed by https://github.com/coreos/fedora-coreos-config/pull/966

**Comment by dustymabe** [comment] 2021-04-21 20:54
The fix for this went into next stream release `34.20210418.1.0`. Please try out the new release and report issues.

**Closed** 2021-04-21 20:54 UTC
Labels: kind/bug
