### ISSUE TITLE
grub: configure other disk as root filesystem

### ISSUE THREAD

**Issue by jjqq2013** [coreos/fedora-coreos-tracker#532] opened 2020-06-10 08:34 UTC
```
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 31.20200505.3.0 (2020-05-19T13:39:46Z)
                    Commit: 01f074cc6cd88d8d2b43f821da692f2367c101eb4377802cb35092bde0ef02f7
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
```

hi, suppose a machine has 2 disk, /dev/sda, /dev/sdb,
due to its firmware limitation, it can only boot from /dev/sda, but it is a slow disk,
so I'd like to install OS itself to /dev/sdb.

Now, I am considering change /boot/grub/grub.cfg or grubenv to accomplish this, it this possible?

- install fcoreos into /dev/sda
- copy it to /dev/sdb
- delete root partition from /dev/sda
- configure root filesystem uuid for grub
```
set root=UUID=......
```

**Comment by lucab** [comment] 2020-06-23 12:40
Closing as a duplicate of #94.

**Closed by lucab** 2020-06-23 12:40 UTC
Labels: component/ignition, kind/new-feature, status/duplicate
