### ISSUE TITLE
podman containers exited after auto-updates

### ISSUE THREAD

**Issue by MrYacha** [coreos/fedora-coreos-tracker#1010] opened 2021-11-04 07:18 UTC
**Describe the bug**
It seems that the new update breaks something and causes podman containers to exits.

The issue is started with upgrading 34.20211004.3.1 to 34.20211016.3.0

The issue assigned a bunch of VMs I'm using.

Rollbacking to 34.20211004.3.1 is works and restored working state

**Symptoms**
Some/All of containers exits whatever they want to, usually, that takes from a few seconds to 2 hours.

**Reproduction steps**
1. Run containers
2. Wait for zincatti to update to the defined version

**System details**
 - Bare Metal (VMs with installed bare-metal ISO)
 - x86_64

**Ignition config**
That doesn't matter for this issue

**Additional information**
The prompt shows that user@1000.service or user@1001.service is failed.

By looking in the journalctl I found some strings that may be related to it:
```
Nov 03 21:01:02 Red systemd[1]: Starting User Manager for UID 1000...
Nov 03 21:01:03 Red systemd[3853]: user@1000.service: Failed to attach to cgroup /user.slice/user-1000.slice/user@1000.service: Device or resource busy
Nov 03 21:01:03 Red systemd[3853]: user@1000.service: Failed at step CGROUP spawning /usr/lib/systemd/systemd: Device or resource busy
Nov 03 21:01:03 Red systemd[1]: user@1000.service: Main process exited, code=exited, status=219/CGROUP
Nov 03 21:01:03 Red systemd[1]: user@1000.service: Killing process 2016 (node) with signal SIGKILL.
Nov 03 21:01:03 Red systemd[1]: user@1000.service: Killing process 2016 (node) with signal SIGKILL.
Nov 03 21:01:03 Red systemd[1]: user@1000.service: Failed with result 'exit-code'.
Nov 03 21:01:03 Red systemd[1]: user@1000.service: Unit process 2016 (node) remains running after unit stopped.
Nov 03 21:01:03 Red systemd[1]: Failed to start User Manager for UID 1000.
```
All of the related VMs had installed firewalld and cronie packages, which might be a key.

Here a podman info output:
```
[op@Viridian ~]$ podman info
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 2
  distribution:
    distribution: fedora
    variant: coreos
    version: "34"
  eventLogger: journald
  hostname: Viridian
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.14.11-200.fc34.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 3557777408
  memTotal: 4104531968
  ociRuntime:
    name: crun
    package: crun-1.2-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.2
      commit: 4f6c8e0583c679bfee6a899c05ac6b916022561b
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc34.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 1073737728
  swapTotal: 1073737728
  uptime: 41.97s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /var/home/op/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/op/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 4
  runRoot: /run/user/1001/containers
  volumePath: /var/home/op/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.0
  Built: 1633030821
  BuiltTime: Thu Sep 30 19:40:21 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.0

WARN[0000] Failed to add pause process to systemd sandbox cgroup: <nil> 
```

**Comment by dustymabe** [comment] 2021-11-04 13:17
Hey @MrYacha - Thanks for the bug report.

I haven't seen anything like this before. Is there any chance you can reproduce this issue reliably and provide some steps here that we can run to also reproduce. That would be key to finding the root cause and getting it fixed.

**Comment by MrYacha** [comment] 2021-11-04 19:09
Hi @dustymabe, as I said I'm having the same issue in half of the VMs I'm using, I can rollback back to the new update and all of them will experience the same issue.
I haven't tried to set up a new CoreOS instance and check out what's going on, I'm going to do that and provide you information.

**Comment by UnixSage** [comment] 2021-11-05 17:34
I too am experiencing strangeness with the latest update. What I am seeing is that containers will exit when I log out. This is new as I have manually restarting them after update. This has been working fine for some time. I see in the logs that the container exited because it got an SIGTERM. Below is from prometheus's alert manager 

level=info ts=2021-11-05T16:00:46.494Z caller=main.go:557 msg="Received SIGTERM, exiting gracefully..."

It is consistent if I stay loged in for an hour it will last an hour if I start and exit it lasts less than a minute..  To be clear I am NOT using systemd to start them and I know I should be just thought calling out this change may be useful.

**Comment by dustymabe** [comment] 2021-11-05 19:15
Hey @UnixSage.  Are these rootless containers (run as a non-root user)? Maybe you need to enable linger for that user. We touch on this a little bit in [the tutorials](https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-user-systemd-unit-on-boot/). You can try on a system that's already booted by running `sudo loginctl enable-linger <user>`.

**Comment by UnixSage** [comment] 2021-11-06 12:14
@dustymabe Gold Star! that did solve my issue!

One interesting data point.

I had not made any changes and this has been running for months without that setting after each auto upgrade I would log in and start the containers without issue. This latest update (34.20211016.3.0) this process came to a screeching halt. So something in this release made this critical.

Thanks for the education none the less..
John

**Comment by dustymabe** [comment] 2022-02-01 15:34
I'm going to close this since we figured out the problem. Not sure exactly what changed but at least we know how to remedy the problem.

**Closed by dustymabe** 2022-02-01 15:34 UTC
Labels: kind/bug
