### ISSUE TITLE
New Package Request: podman-quadlet

### ISSUE THREAD

**Issue by ondrejbudai** [coreos/fedora-coreos-tracker#1406] opened 2023-02-03 09:37 UTC
`podman-quadlet` was released alongside podman 4.4 yesterday. It's a new and trivial way of managing podman containers using `systemd`. Since Fedora CoreOS' main use-case is running containerized workloads, I think that the inclusion of this new package could be beneficial for many users who want a dead simple way to run containers as a system service.

I consider the risk of adding this new package minimal. If you don't create a `.service` or `.volume` unit file, `podman-quadlet` shouldn't do literally anything. The size of the package is roughly 2MiB (it's a Go binary).

See https://github.com/containers/podman/blob/main/docs/source/markdown/podman-systemd.unit.5.md for documentation.

cc @alexlarsson

**Comment by travier** [comment] 2023-02-03 10:02
Duplicate of https://github.com/coreos/fedora-coreos-tracker/issues/998

**Closed by travier** 2023-02-03 10:02 UTC
