### ISSUE TITLE
broken toolbox in f32

### ISSUE THREAD

**Issue by grantral** [coreos/fedora-coreos-tracker#535] opened 2020-06-11 10:47 UTC
## Steps to reproduce and actual behaviour
1. `$ toolbox create`
2. `$ toolbox enter`
```
toolbox: failed to start container fedora-toolbox-32
```
3. `$ toolbox list`
```
IMAGE ID      IMAGE NAME                                        CREATED
fe7b8c2393f9  registry.fedoraproject.org/f32/fedora-toolbox:32  7 weeks ago

CONTAINER ID  CONTAINER NAME     CREATED         STATUS   IMAGE NAME
ae8d3f53ae8b  fedora-toolbox-32  23 minutes ago  Created  registry.fedoraproject.org/f32/fedora-toolbox:32
```
4. `$ podman start fedora-toolbox-32`
```
Error: unable to start container "fedora-toolbox-32": error looking up supplemental groups for container ae8d3f53ae8b929ff3795eee5c976158b010f18221ea2e61e8a121829b9c9a82: Unable to find group sudo
```
5. `$ groups`
```
core adm wheel sudo systemd-journal
```

### Ignition config
```
variant: fcos
version: 1.1.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc...
```

### rpm-ostree status
```
State: idle
Deployments:
● ostree://fedora:fedora/x86_64/coreos/next
                   Version: 32.20200601.1.1 (2020-06-03T02:26:26Z)
                    Commit: 08040bebbab87a3343a281f94bb68010df618eb6ce6ac3d4230d2595959b5da1
              GPGSignature: Valid signature by 97A1AE57C3A2372CCA3A4ABA6C13026D12C944D0
```

**Comment by lucab** [comment] 2020-06-11 11:03
I think this is a duplicate of https://github.com/coreos/fedora-coreos-tracker/issues/458, which goes back to upstream https://github.com/containers/toolbox/issues/423.

I'm inclined to close this to avoid keeping duplicates, but feel free to ping back on the upstream ticket directly.

**Comment by lucab** [comment] 2020-06-15 12:14
Duplicate of #458.

**Closed by lucab** 2020-06-15 12:14 UTC
Labels: component/toolbox, kind/bug
