### ISSUE TITLE
xfsprogs 6.1.0 disallows creating filesystems smaller than 300 MB

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#1443] opened 2023-03-21 07:13 UTC
[xfsprogs-6.1.0-1.fc37](https://bodhi.fedoraproject.org/updates/FEDORA-2023-e1b65ce960) [removes support](https://git.kernel.org/pub/scm/fs/xfs/xfsprogs-dev.git/commit/?id=6e0ed3d19c54603f0f7d628ea04b550151d8a262) for creating filesystems under 300 MB unless `--unsupported` is specified.  This change contravenes policy for Fedora Linux 37 ([bug](https://bugzilla.redhat.com/show_bug.cgi?id=2180289)) but is fair game for Fedora 38.  When it reaches Fedora CoreOS streams this week, it will cause a regression for any Ignition config that creates such a filesystem (provisioning will fail).  However, such small filesystems are probably not too common.  (Though I could imagine someone creating e.g. a separate `/var/log` in a small VM.)

Should we pin xfsprogs and/or post to coreos-status for this?

**Comment by dustymabe** [comment] 2023-03-21 12:49
> Should we pin xfsprogs and/or post to coreos-status for this?

Maybe pin in F37 streams (`testing`/`stable`) and send a status post. Leave it unpinned in F38.

**Comment by bgilbert** [comment] 2023-03-21 17:47
Pin in https://github.com/coreos/fedora-coreos-config/pull/2309.

**Comment by dustymabe** [comment] 2023-03-22 17:32
We discussed this in the [community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/DYBQUURSUDPMX47YH2CYKYJGAANFKSDN/).


```
12:51:54* dustymabe | #agreed we'll keep this pinned in f37 for now and introduce the
                    | change with the f38 rebase in each stream. we won't put out a
                    | coreos-status post as we think the use case is relatively
                    | uncommon. 

```

**Comment by dustymabe** [comment] 2023-03-22 17:34
We usually update release notes when a "fix" lands in a stream, but in this case it's a regression we're introducing, which makes it a bit odd for our normal release notes/"this was fixed in XYZ" messages that we do.

Ideas on how this should be handled in release notes and GH "fixed in" messages?

**Comment by dustymabe** [comment] 2023-03-25 02:17
questions above still stand

**Comment by jlebon** [comment] 2023-03-28 19:30
Maybe we should extend the release notes schema and website to have a "Changes" section. (And while we're here, maybe also a "New Features" section?)

**Comment by dustymabe** [comment] 2023-04-06 21:25
The strict behavior was reverted in Fedora 37 in `xfsprogs-6.1.0-2.fc37` and it made it into `testing-devel` in https://github.com/coreos/fedora-coreos-config/pull/2327.

It is worth noting that the strict behavior will remain in F38 (`next`) and will eventually come to `testing` and `stable`.

**Comment by dustymabe** [comment] 2023-04-06 21:28
This "regression" never made it into our `testing` or `stable` streams (based on F37) because we caught it early enough so I'll close this out now.

(note that the behavior change is coming in the switch to F38, though).

**Closed by dustymabe** 2023-04-06 21:28 UTC
Labels: area/usability, kind/regression, status/pending-testing-release
