### ISSUE TITLE
m6i instances fail to boot - kernel crashlooping

### ISSUE THREAD

**Issue by vrutkovs** [coreos/fedora-coreos-tracker#1004] opened 2021-10-28 14:19 UTC
**Describe the bug**
m6i AWS instance family cannot be used with FCOS - kernel crashes on start time

**Reproduction steps**
1. Launch latest stable FCOS (34.20211004.3.1) using m6i.large
2. Check boot messages

**Expected behavior**
The instance boots

**Actual behavior**
Kernel crash

**System details**
 - AWS. AWS m5 or GCP's n4-standard is fine
 - Fedora CoreOS version - 34.20211004.3.1 (stable) / 35.20211017.1.0 (next)

**Ignition config**
Not required

**Additional information**
This seems to be a kernel regression - reverting kernel to `5.13.14-200.fc34` makes the instance boot correctly.
AWS won't let me save the whole console log, so here's a partial screenshot of the stack trace 
![i-09a2dcd8b9186cf5e](https://user-images.githubusercontent.com/114501/139274979-2850d695-8d7b-46fc-bcd6-e64db65c7294.jpg)

OKD 4.10 installer uses `m6i` family by default, so OKD has to [pin kernel to 5.13](https://github.com/openshift/okd-machine-os/commit/44dea05c184b65d1e9781041548ab20c197aa647). This also prevents us from testing `next`/`rawhide` stream

**Comment by bgilbert** [comment] 2021-10-29 21:10
@vrutkovs Could you file a Fedora kernel BZ for this?  We're unlikely to be able to do a lot about it directly in FCOS.

**Comment by dustymabe** [comment] 2021-11-01 16:18
I'm able to reproduce. Have asked @davdunc to take a look to see if there are any known issues with 5.14+ kernels that AWS is aware of.

**Comment by davdunc** [comment] 2021-11-01 23:27
EC2 internally tracking at V461091694.

**Comment by davdunc** [comment] 2021-11-02 23:54
A workaround is to add intel_pstate=disable to the kernel commandline

**Comment by davdunc** [comment] 2021-11-02 23:56
Because ICELAKE_X was added to intel_pstate_cpu_ids but not to intel_pstate_cpu_oob_ids the driver wrongly tries to init the pstate driver.

The ICX documentation for MSR 0x1aa states:

Bit 8:

Enable Autonomous Out of Band (ENABLE_OUT_OF_BAND_AUTONOMOUS):
Setting this bit (1) will enable HWP with its default settings but without the ability for
software to access HWP MSRs. This bit can be set only if Enumerate HWP bit is clear,
MISC_PWR_MGT[6] (0).

This seems to be a upstream regression

**Comment by davdunc** [comment] 2021-11-03 00:01
Didn't want to paste this into the content, but you can find a full stack trace here: https://paste.centos.org/view/cdf268e1 for the next 24 hours.

**Comment by dustymabe** [comment] 2021-11-03 14:02
Thanks @davdunc for digging in.

> This seems to be a upstream regression

i.e. there should be a kernel patch upstream soon that we can backport?

**Comment by davdunc** [comment] 2021-11-10 12:23
This is where the issue first appears: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/drivers/cpufreq/intel_pstate.c?h=v5.14.15&id=fbdc21e9b038d00d0d56fa4e0f7701d42ae08f00

**Comment by dustymabe** [comment] 2021-11-10 15:18
Thanks @davdunc - Do you know if there is a proposed fix yet?

**Comment by davdunc** [comment] 2021-11-11 18:09
not in the EC2 engineering review @dustymabe I'll try to determine what we need to do herel

**Comment by davdunc** [comment] 2021-11-28 03:28
Patch submitted to mainline kernel https://lkml.org/lkml/2021/11/12/115

**Comment by dustymabe** [comment] 2021-12-08 15:17
Looks like this will be in kernel `5.16` when it's released but was also backported to [`5.15.6`](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=d10ecfd). Let's confirm it's fixed in the latest `testing` and also add `m6i.large` to the list of instance types we run basic tests on. See the [existing test](https://github.com/coreos/fedora-coreos-pipeline/blob/main/jobs/kola-aws.Jenkinsfile#L75-L90) where we run a extra test for `m4.large` already).

**Comment by dustymabe** [comment] 2021-12-21 20:05
https://github.com/coreos/fedora-coreos-pipeline/pull/450 adds a test for this.

**Comment by dustymabe** [comment] 2021-12-21 20:07
The fix for this went into testing stream release `35.20211203.2.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment] 2021-12-21 20:07
The fix for this went into stable stream release `35.20211203.3.0`.

**Closed by dustymabe** 2021-12-21 20:07 UTC
Labels: kind/bug, jira, component/kernel, kind/regression, area/upstream
